cmake_minimum_required(VERSION 3.13)

if(NOT DEFINED BUILD_DIR OR BUILD_DIR STREQUAL "")
  message(FATAL_ERROR "BUILD_DIR must name a configured Orange build tree")
endif()

if(NOT DEFINED INSTALL_PREFIX OR INSTALL_PREFIX STREQUAL "")
  set(INSTALL_PREFIX "/app")
endif()

set(APP_ID "com.goshapps.Orange")
set(LEGACY_APP_ID "org.orangemusicplayer.orange")
set(STAGE_ROOT "${BUILD_DIR}/desktop-integration-install-root")

file(REMOVE_RECURSE "${STAGE_ROOT}")
file(MAKE_DIRECTORY "${STAGE_ROOT}")

set(previous_destdir "$ENV{DESTDIR}")
set(ENV{DESTDIR} "${STAGE_ROOT}")
execute_process(
  COMMAND "${CMAKE_COMMAND}" --install "${BUILD_DIR}" --prefix "${INSTALL_PREFIX}" --component desktop_integration
  RESULT_VARIABLE install_result
  OUTPUT_VARIABLE install_output
  ERROR_VARIABLE install_error
)
set(ENV{DESTDIR} "${previous_destdir}")

if(NOT install_result EQUAL 0)
  message(FATAL_ERROR "Orange desktop-integration component install failed (${install_result})\n${install_output}\n${install_error}")
endif()

string(REGEX REPLACE "^/+" "" install_prefix_relative "${INSTALL_PREFIX}")
set(INSTALL_ROOT "${STAGE_ROOT}/${install_prefix_relative}")
set(DESKTOP_FILE "${INSTALL_ROOT}/share/applications/${APP_ID}.desktop")
set(APPSTREAM_FILE "${INSTALL_ROOT}/share/metainfo/${APP_ID}.appdata.xml")

function(assert_file_exists absolute_path)
  if(NOT EXISTS "${absolute_path}" OR IS_DIRECTORY "${absolute_path}")
    message(FATAL_ERROR "Expected installed Orange file does not exist: ${absolute_path}\nInstall output:\n${install_output}")
  endif()
endfunction()

function(assert_file_absent absolute_path)
  if(EXISTS "${absolute_path}")
    message(FATAL_ERROR "Obsolete installed Orange identity still exists: ${absolute_path}")
  endif()
endfunction()

function(assert_file_contains absolute_path expected)
  assert_file_exists("${absolute_path}")
  file(READ "${absolute_path}" contents)
  string(FIND "${contents}" "${expected}" position)
  if(position EQUAL -1)
    message(FATAL_ERROR "${absolute_path} does not contain: ${expected}")
  endif()
endfunction()

function(assert_file_excludes_case_insensitive absolute_path unexpected)
  assert_file_exists("${absolute_path}")
  file(READ "${absolute_path}" contents)
  string(TOLOWER "${contents}" contents_lower)
  string(TOLOWER "${unexpected}" unexpected_lower)
  string(FIND "${contents_lower}" "${unexpected_lower}" position)
  if(NOT position EQUAL -1)
    message(FATAL_ERROR "${absolute_path} still contains obsolete launcher identity: ${unexpected}")
  endif()
endfunction()

function(assert_desktop_value key expected)
  assert_file_exists("${DESKTOP_FILE}")
  file(READ "${DESKTOP_FILE}" desktop_contents)
  string(REGEX MATCH "(^|\n)${key}=([^\r\n]*)" desktop_match "${desktop_contents}")
  if(NOT desktop_match)
    message(FATAL_ERROR "Installed desktop entry is missing ${key}=: ${DESKTOP_FILE}")
  endif()
  set(actual "${CMAKE_MATCH_2}")
  if(NOT actual STREQUAL expected)
    message(FATAL_ERROR "Installed desktop ${key}= mismatch: expected '${expected}', got '${actual}'")
  endif()
endfunction()

function(assert_valid_png absolute_path expected_size)
  assert_file_exists("${absolute_path}")
  get_filename_component(icon_filename "${absolute_path}" NAME)
  if(NOT icon_filename STREQUAL "${APP_ID}.png")
    message(FATAL_ERROR "Installed PNG has the wrong Flatpak/KDE icon name: ${absolute_path}")
  endif()

  if(expected_size EQUAL 16)
    set(expected_dimension_hex "00000010")
  elseif(expected_size EQUAL 22)
    set(expected_dimension_hex "00000016")
  elseif(expected_size EQUAL 32)
    set(expected_dimension_hex "00000020")
  elseif(expected_size EQUAL 48)
    set(expected_dimension_hex "00000030")
  elseif(expected_size EQUAL 64)
    set(expected_dimension_hex "00000040")
  elseif(expected_size EQUAL 128)
    set(expected_dimension_hex "00000080")
  else()
    message(FATAL_ERROR "Test has no PNG dimension mapping for ${expected_size}")
  endif()

  file(READ "${absolute_path}" png_hex HEX)
  string(TOLOWER "${png_hex}" png_hex)
  string(LENGTH "${png_hex}" png_hex_length)
  if(png_hex_length LESS 64)
    message(FATAL_ERROR "Installed PNG is truncated: ${absolute_path}")
  endif()

  string(SUBSTRING "${png_hex}" 0 32 png_header)
  if(NOT png_header STREQUAL "89504e470d0a1a0a0000000d49484452")
    message(FATAL_ERROR "Installed file is not a structurally valid PNG with an IHDR first chunk: ${absolute_path}")
  endif()
  string(SUBSTRING "${png_hex}" 32 8 png_width)
  string(SUBSTRING "${png_hex}" 40 8 png_height)
  if(NOT png_width STREQUAL expected_dimension_hex OR NOT png_height STREQUAL expected_dimension_hex)
    message(FATAL_ERROR "Installed PNG dimensions do not match ${expected_size}x${expected_size}: ${absolute_path}")
  endif()
  string(FIND "${png_hex}" "49444154" idat_position)
  if(idat_position EQUAL -1)
    message(FATAL_ERROR "Installed PNG has no IDAT image-data chunk: ${absolute_path}")
  endif()
  math(EXPR png_suffix_start "${png_hex_length} - 24")
  string(SUBSTRING "${png_hex}" ${png_suffix_start} 24 png_suffix)
  if(NOT png_suffix STREQUAL "0000000049454e44ae426082")
    message(FATAL_ERROR "Installed PNG has no valid IEND trailer: ${absolute_path}")
  endif()
endfunction()

function(assert_valid_svg absolute_path)
  assert_file_exists("${absolute_path}")
  get_filename_component(icon_filename "${absolute_path}" NAME)
  if(NOT icon_filename STREQUAL "${APP_ID}.svg")
    message(FATAL_ERROR "Installed SVG has the wrong Flatpak/KDE icon name: ${absolute_path}")
  endif()
  assert_file_contains("${absolute_path}" "<svg")
  assert_file_contains("${absolute_path}" "xmlns=\"http://www.w3.org/2000/svg\"")
  assert_file_contains("${absolute_path}" "viewBox=")
  assert_file_contains("${absolute_path}" "</svg>")
  assert_file_excludes_case_insensitive("${absolute_path}" "strawberry")
endfunction()

# The exported desktop entry name, freedesktop icon name, executable, and Wayland identity must agree.
assert_desktop_value("Type" "Application")
assert_desktop_value("Name" "Orange")
assert_desktop_value("Exec" "orange %U")
assert_desktop_value("Icon" "${APP_ID}")
assert_desktop_value("X-KDE-WaylandAppId" "${APP_ID}")
assert_file_excludes_case_insensitive("${DESKTOP_FILE}" "strawberry")
assert_file_excludes_case_insensitive("${DESKTOP_FILE}" "TryExec=")

# Install exact-size menu icons plus a scalable fallback under the same app-ID basename.
foreach(size 16 22 32 48 64 128)
  assert_valid_png("${INSTALL_ROOT}/share/icons/hicolor/${size}x${size}/apps/${APP_ID}.png" ${size})
endforeach()
assert_valid_svg("${INSTALL_ROOT}/share/icons/hicolor/scalable/apps/${APP_ID}.svg")

file(GLOB_RECURSE installed_icon_files LIST_DIRECTORIES false "${INSTALL_ROOT}/share/icons/hicolor/*/apps/*")
list(LENGTH installed_icon_files installed_icon_count)
if(NOT installed_icon_count EQUAL 7)
  message(FATAL_ERROR "Desktop-integration component installed ${installed_icon_count} icon files; expected six PNG sizes and one scalable SVG: ${installed_icon_files}")
endif()
foreach(installed_icon IN LISTS installed_icon_files)
  string(TOLOWER "${installed_icon}" installed_icon_lower)
  string(FIND "${installed_icon_lower}" "strawberry" strawberry_position)
  if(NOT strawberry_position EQUAL -1)
    message(FATAL_ERROR "Installed/exportable icon path exposes Strawberry identity: ${installed_icon}")
  endif()
endforeach()

# AppStream must launch the exact desktop ID and advertise the same stock icon and executable.
assert_file_contains("${APPSTREAM_FILE}" "<id>${APP_ID}</id>")
assert_file_contains("${APPSTREAM_FILE}" "<launchable type=\"desktop-id\">${APP_ID}.desktop</launchable>")
assert_file_contains("${APPSTREAM_FILE}" "<icon type=\"stock\">${APP_ID}</icon>")
assert_file_contains("${APPSTREAM_FILE}" "<binary>orange</binary>")
assert_file_contains("${APPSTREAM_FILE}" "<name>Orange Music Player</name>")
assert_file_contains("${APPSTREAM_FILE}" "<name>Gosh</name>")

assert_file_absent("${INSTALL_ROOT}/share/applications/${LEGACY_APP_ID}.desktop")
assert_file_absent("${INSTALL_ROOT}/share/metainfo/${LEGACY_APP_ID}.appdata.xml")
assert_file_absent("${INSTALL_ROOT}/share/icons/hicolor/32x32/apps/strawberry.png")

message(STATUS "Orange installed/Flatpak-exportable desktop integration checks passed")
