cmake_minimum_required(VERSION 3.13)

get_filename_component(SOURCE_ROOT "${CMAKE_CURRENT_LIST_DIR}/.." ABSOLUTE)
set(APP_ID "com.goshapps.Orange")
set(APP_ICON_SOURCE "data/icons/scalable/${APP_ID}.svg")

function(assert_file_exists relative_path)
  if(NOT EXISTS "${SOURCE_ROOT}/${relative_path}")
    message(FATAL_ERROR "Expected Orange branding file does not exist: ${relative_path}")
  endif()
endfunction()

function(assert_file_contains relative_path expected)
  file(READ "${SOURCE_ROOT}/${relative_path}" contents)
  string(FIND "${contents}" "${expected}" position)
  if(position EQUAL -1)
    message(FATAL_ERROR "${relative_path} does not contain: ${expected}")
  endif()
endfunction()

function(assert_file_excludes relative_path unexpected)
  file(READ "${SOURCE_ROOT}/${relative_path}" contents)
  string(FIND "${contents}" "${unexpected}" position)
  if(NOT position EQUAL -1)
    message(FATAL_ERROR "${relative_path} still contains obsolete branding: ${unexpected}")
  endif()
endfunction()

# One original scalable Orange mark is the source of the KDE icon and bundled raster fallbacks.
assert_file_exists("${APP_ICON_SOURCE}")
assert_file_contains("${APP_ICON_SOURCE}" "Orange application icon")
foreach(size 16 22 32 48 64 128)
  assert_file_exists("data/icons/${size}x${size}/${APP_ID}.png")
  assert_file_contains("data/icons.qrc" "icons/${size}x${size}/${APP_ID}.png")
endforeach()

# KDE, the desktop entry, and AppStream must resolve the same freedesktop icon name.
assert_file_contains("dist/unix/${APP_ID}.desktop" "Icon=${APP_ID}")
assert_file_contains("dist/unix/${APP_ID}.appdata.xml" "<icon type=\"stock\">${APP_ID}</icon>")
assert_file_contains("dist/unix/${APP_ID}.appdata.xml" "<category>KDE</category>")
assert_file_contains("dist/unix/${APP_ID}.appdata.xml" "<category>Audio</category>")
assert_file_excludes("dist/unix/${APP_ID}.appdata.xml" "strawberrymusicplayer.org")
assert_file_excludes("dist/unix/${APP_ID}.appdata.xml" "<update_contact>")
assert_file_contains("dist/CMakeLists.txt" "data/icons/scalable/${APP_ID}.svg")
assert_file_contains("dist/CMakeLists.txt" "share/icons/hicolor/scalable/apps")
foreach(size 16 22 32 48 64 128)
  assert_file_contains("dist/CMakeLists.txt" "data/icons/${size}x${size}/${APP_ID}.png")
  assert_file_contains("dist/CMakeLists.txt" "share/icons/hicolor/${size}x${size}/apps")
endforeach()
assert_file_excludes("dist/CMakeLists.txt" "data/icons/48x48/strawberry.png")
assert_file_excludes("dist/CMakeLists.txt" "data/icons/64x64/strawberry.png")
assert_file_excludes("dist/CMakeLists.txt" "data/icons/128x128/strawberry.png")

# Runtime application surfaces must ask for the canonical app icon, not Strawberry's themed icon.
assert_file_contains("src/main.cpp" "IconLoader::Load(u\"${APP_ID}\"_s)")
assert_file_contains("src/core/mainwindow.cpp" "IconLoader::Load(u\"${APP_ID}\"_s)")
assert_file_contains("src/systemtrayicon/qtsystemtrayicon.cpp" "IconLoader::Load(u\"${APP_ID}\"_s)")
assert_file_excludes("src/main.cpp" "IconLoader::Load(u\"strawberry\"_s)")
assert_file_excludes("src/core/mainwindow.cpp" "IconLoader::Load(u\"strawberry\"_s)")
assert_file_excludes("src/systemtrayicon/qtsystemtrayicon.cpp" "IconLoader::Load(u\"strawberry\"_s)")
assert_file_contains("src/systemtrayicon/macsystemtrayicon.mm" ":/icons/128x128/${APP_ID}.png")
assert_file_contains("src/systemtrayicon/macsystemtrayicon.mm" ":/icons/128x128/${APP_ID}-grey.png")
assert_file_excludes("src/systemtrayicon/macsystemtrayicon.mm" ":/pictures/strawberry.png")
assert_file_excludes("src/systemtrayicon/macsystemtrayicon.mm" ":/pictures/strawberry-grey.png")

# The collection's empty state must use dedicated Orange artwork and expose no strawberry image.
assert_file_exists("data/pictures/collection-empty.png")
assert_file_exists("data/pictures/collection-empty.svg")
assert_file_exists("data/pictures/orange-faded.png")
assert_file_contains("data/pictures/collection-empty.svg" "Orange empty-collection artwork")
assert_file_contains("data/data.qrc" "pictures/collection-empty.png")
assert_file_contains("src/collection/collectionview.cpp" ":/pictures/collection-empty.png")
assert_file_excludes("src/collection/collectionview.cpp" ":/pictures/nomusic.png")
assert_file_excludes("src/collection/collectionview.cpp" "confused strawberry")
assert_file_contains("src/streaming/streamingcollectionview.cpp" ":/pictures/collection-empty.png")
assert_file_excludes("src/streaming/streamingcollectionview.cpp" ":/pictures/nomusic.png")
assert_file_excludes("src/streaming/streamingcollectionview.cpp" "confused strawberry")
assert_file_contains("data/data.qrc" "pictures/orange-faded.png")
assert_file_excludes("data/data.qrc" "pictures/strawberry-faded.png")
assert_file_contains("data/style/strawberry.css" ":pictures/orange-faded.png")
assert_file_excludes("data/style/strawberry.css" ":pictures/strawberry-faded.png")

message(STATUS "Orange KDE icon and empty-collection artwork checks passed")
