cmake_minimum_required(VERSION 3.13)

get_filename_component(SOURCE_ROOT "${CMAKE_CURRENT_LIST_DIR}/.." ABSOLUTE)
set(APP_ID "com.goshapps.Orange")
set(LEGACY_APP_ID "org.orangemusicplayer.orange")
set(RELEASE_VERSION "2.1.5")
set(RELEASE_DATE "2026-09-01")

function(assert_file_exists relative_path)
  if(NOT EXISTS "${SOURCE_ROOT}/${relative_path}")
    message(FATAL_ERROR "Expected file does not exist: ${relative_path}")
  endif()
endfunction()

function(assert_file_absent relative_path)
  if(EXISTS "${SOURCE_ROOT}/${relative_path}")
    message(FATAL_ERROR "Legacy identity file still exists: ${relative_path}")
  endif()
endfunction()

function(assert_file_contains relative_path expected)
  file(READ "${SOURCE_ROOT}/${relative_path}" contents)
  string(FIND "${contents}" "${expected}" position)
  if(position EQUAL -1)
    message(FATAL_ERROR "${relative_path} does not contain: ${expected}")
  endif()
endfunction()

function(assert_file_excludes relative_path unexpected)
  file(READ "${SOURCE_ROOT}/${relative_path}" contents)
  string(FIND "${contents}" "${unexpected}" position)
  if(NOT position EQUAL -1)
    message(FATAL_ERROR "${relative_path} still contains: ${unexpected}")
  endif()
endfunction()

function(assert_file_order relative_path earlier later)
  file(READ "${SOURCE_ROOT}/${relative_path}" contents)
  string(FIND "${contents}" "${earlier}" earlier_position)
  string(FIND "${contents}" "${later}" later_position)
  if(earlier_position EQUAL -1 OR later_position EQUAL -1 OR NOT earlier_position LESS later_position)
    message(FATAL_ERROR "${relative_path} does not order '${earlier}' before '${later}'")
  endif()
endfunction()

assert_file_exists("dist/unix/${APP_ID}.desktop")
assert_file_exists("dist/unix/${APP_ID}.appdata.xml")
assert_file_absent("dist/unix/${LEGACY_APP_ID}.desktop")
assert_file_absent("dist/unix/${LEGACY_APP_ID}.appdata.xml")

assert_file_contains("dist/unix/${APP_ID}.desktop" "Icon=${APP_ID}")
assert_file_contains("dist/unix/${APP_ID}.desktop" "Exec=orange %U")
assert_file_contains("dist/unix/${APP_ID}.desktop" "X-KDE-WaylandAppId=${APP_ID}")
assert_file_excludes("dist/unix/${APP_ID}.desktop" "TryExec=")
assert_file_excludes("dist/unix/${APP_ID}.desktop" "Keywords=Audio;Player;Strawberry;Clementine;")
assert_file_contains("dist/unix/${APP_ID}.appdata.xml" "<id>${APP_ID}</id>")
assert_file_contains("dist/unix/${APP_ID}.appdata.xml" "<launchable type=\"desktop-id\">${APP_ID}.desktop</launchable>")
assert_file_contains("dist/unix/${APP_ID}.appdata.xml" "<name>Gosh</name>")
assert_file_contains("dist/unix/${APP_ID}.appdata.xml" "<release version=\"${RELEASE_VERSION}\" date=\"${RELEASE_DATE}\"/>")

assert_file_contains("dist/CMakeLists.txt" "data/icons/scalable/${APP_ID}.svg")
assert_file_contains("dist/CMakeLists.txt" "unix/${APP_ID}.desktop")
assert_file_contains("dist/CMakeLists.txt" "unix/${APP_ID}.appdata.xml")
assert_file_excludes("dist/CMakeLists.txt" "${LEGACY_APP_ID}")
assert_file_contains("dist/unix/strawberry.spec.in" "applications/${APP_ID}.desktop")
assert_file_contains("dist/unix/strawberry.spec.in" "metainfo/${APP_ID}.appdata.xml")
assert_file_contains("dist/unix/strawberry.spec.in" "apps/${APP_ID}.*")
assert_file_contains("dist/macos/Info.plist.in" "<string>${APP_ID}</string>")
assert_file_contains(".github/workflows/build.yaml" "AppDir/usr/share/applications/${APP_ID}.desktop")
assert_file_excludes(".github/workflows/build.yaml" "AppDir/usr/share/applications/${LEGACY_APP_ID}.desktop")

assert_file_contains("src/main.cpp" "setDesktopFileName(u\"${APP_ID}\"_s)")
assert_file_contains("src/main.cpp" "PULSE_PROP_application.icon_name\", \"${APP_ID}\"")
assert_file_excludes("src/main.cpp" "${LEGACY_APP_ID}")
assert_file_order("src/main.cpp" "if (!options.Parse()) return 1;" "KDSingleApplication single_app(QCoreApplication::applicationName().toLower()")
assert_file_contains("src/core/mainwindow.cpp" "application://${APP_ID}.desktop")
assert_file_contains("src/core/mainwindow.cpp" "u\"/com/goshapps/Orange\"_s")
assert_file_excludes("src/core/mainwindow.cpp" "${LEGACY_APP_ID}")
assert_file_contains("src/mpris2/mpris2.cpp" "org.mpris.MediaPlayer2.orange")
assert_file_contains("src/mpris2/mpris2.cpp" "\"/com/goshapps/Orange/Track/\"")
assert_file_contains("src/mpris2/mpris2.cpp" "\"/com/goshapps/Orange/PlaylistId/%1\"")
assert_file_excludes("src/mpris2/mpris2.cpp" "/org/orangemusicplayer/orange/")

# Desktop catalog identity must not move existing user data or QSettings.
assert_file_contains("src/main.cpp" "setApplicationName(u\"Orange\"_s)")
assert_file_contains("src/main.cpp" "setOrganizationName(u\"Orange\"_s)")
assert_file_contains("src/main.cpp" "setOrganizationDomain(u\"strawberrymusicplayer.org\"_s)")
assert_file_contains("src/core/database.cpp" "kDatabaseFilename[] = \"orange.db\"")
assert_file_contains("src/core/settings.cpp" "organizationName().toLower(), QCoreApplication::applicationName().toLower()")
assert_file_contains("src/core/standardpaths.cpp" "AppendOrganizationAndApplication")

assert_file_contains("cmake/Version.cmake" "set(STRAWBERRY_VERSION_PATCH 5)")
assert_file_contains("README.md" "**Current release:** ${RELEASE_VERSION}")
assert_file_contains("README.md" "**Maker:** Gosh")
assert_file_contains("README.md" "catalog identity does not rename")
assert_file_contains("Changelog" "Version ${RELEASE_VERSION} (2026.09.01):")
assert_file_contains("src/dialogs/aboutdialog.cpp" "tr(\"Maker: Gosh\")")

message(STATUS "Orange ${RELEASE_VERSION} canonical identity metadata checks passed")
