// This file is automatically generated, so please do not edit it.
// @generated by `flutter_rust_bridge`@ 2.13.0.

// ignore_for_file: unused_import, unused_element, unnecessary_import, duplicate_ignore, invalid_use_of_internal_member, annotate_overrides, non_constant_identifier_names, curly_braces_in_flow_control_structures, prefer_const_literals_to_create_immutables, unused_field

import 'api/models.dart';
import 'api/session.dart';

import 'dart:async';
import 'dart:convert';
import 'dart:ffi' as ffi;

import 'frb_generated.dart';

import 'package:flutter_rust_bridge/flutter_rust_bridge_for_generated_io.dart';

abstract class RustLibApiImplPlatform extends BaseApiImpl<RustLibWire> {
  RustLibApiImplPlatform({
    required super.handler,
    required super.wire,
    required super.generalizedFrbRustBinding,
    required super.portManager,
  });

  CrossPlatformFinalizerArg
  get rust_arc_decrement_strong_count_SessionPtr => wire
      ._rust_arc_decrement_strong_count_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerSessionPtr;

  @protected
  Session
  dco_decode_Auto_Owned_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerSession(
    dynamic raw,
  );

  @protected
  Session
  dco_decode_Auto_Ref_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerSession(
    dynamic raw,
  );

  @protected
  int dco_decode_CastedPrimitive_i_64(dynamic raw);

  @protected
  int dco_decode_CastedPrimitive_u_64(dynamic raw);

  @protected
  Session
  dco_decode_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerSession(
    dynamic raw,
  );

  @protected
  String dco_decode_String(dynamic raw);

  @protected
  bool dco_decode_bool(dynamic raw);

  @protected
  Command dco_decode_box_autoadd_command(dynamic raw);

  @protected
  LibraryQuery dco_decode_box_autoadd_library_query(dynamic raw);

  @protected
  TagEdit dco_decode_box_autoadd_tag_edit(dynamic raw);

  @protected
  TrackDto dco_decode_box_autoadd_track_dto(dynamic raw);

  @protected
  int dco_decode_box_autoadd_u_32(dynamic raw);

  @protected
  BridgeFailure dco_decode_bridge_failure(dynamic raw);

  @protected
  CatalogDto dco_decode_catalog_dto(dynamic raw);

  @protected
  Command dco_decode_command(dynamic raw);

  @protected
  ConversionTargetDto dco_decode_conversion_target_dto(dynamic raw);

  @protected
  double dco_decode_f_32(dynamic raw);

  @protected
  double dco_decode_f_64(dynamic raw);

  @protected
  FailureKind dco_decode_failure_kind(dynamic raw);

  @protected
  FileEntryDto dco_decode_file_entry_dto(dynamic raw);

  @protected
  int dco_decode_i_32(dynamic raw);

  @protected
  PlatformInt64 dco_decode_i_64(dynamic raw);

  @protected
  LibraryPage dco_decode_library_page(dynamic raw);

  @protected
  LibraryQuery dco_decode_library_query(dynamic raw);

  @protected
  List<String> dco_decode_list_String(dynamic raw);

  @protected
  List<ConversionTargetDto> dco_decode_list_conversion_target_dto(dynamic raw);

  @protected
  List<FileEntryDto> dco_decode_list_file_entry_dto(dynamic raw);

  @protected
  List<NamedItem> dco_decode_list_named_item(dynamic raw);

  @protected
  Float32List dco_decode_list_prim_f_32_strict(dynamic raw);

  @protected
  Float64List dco_decode_list_prim_f_64_strict(dynamic raw);

  @protected
  Uint8List dco_decode_list_prim_u_8_strict(dynamic raw);

  @protected
  List<StationDto> dco_decode_list_station_dto(dynamic raw);

  @protected
  List<TrackDto> dco_decode_list_track_dto(dynamic raw);

  @protected
  NamedItem dco_decode_named_item(dynamic raw);

  @protected
  String? dco_decode_opt_String(dynamic raw);

  @protected
  TrackDto? dco_decode_opt_box_autoadd_track_dto(dynamic raw);

  @protected
  int? dco_decode_opt_box_autoadd_u_32(dynamic raw);

  @protected
  PlaybackDto dco_decode_playback_dto(dynamic raw);

  @protected
  PlaybackState dco_decode_playback_state(dynamic raw);

  @protected
  PreferencesDto dco_decode_preferences_dto(dynamic raw);

  @protected
  SmartView dco_decode_smart_view(dynamic raw);

  @protected
  StationDto dco_decode_station_dto(dynamic raw);

  @protected
  TagEdit dco_decode_tag_edit(dynamic raw);

  @protected
  TrackDto dco_decode_track_dto(dynamic raw);

  @protected
  int dco_decode_u_32(dynamic raw);

  @protected
  BigInt dco_decode_u_64(dynamic raw);

  @protected
  int dco_decode_u_8(dynamic raw);

  @protected
  void dco_decode_unit(dynamic raw);

  @protected
  BigInt dco_decode_usize(dynamic raw);

  @protected
  Session
  sse_decode_Auto_Owned_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerSession(
    SseDeserializer deserializer,
  );

  @protected
  Session
  sse_decode_Auto_Ref_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerSession(
    SseDeserializer deserializer,
  );

  @protected
  int sse_decode_CastedPrimitive_i_64(SseDeserializer deserializer);

  @protected
  int sse_decode_CastedPrimitive_u_64(SseDeserializer deserializer);

  @protected
  Session
  sse_decode_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerSession(
    SseDeserializer deserializer,
  );

  @protected
  String sse_decode_String(SseDeserializer deserializer);

  @protected
  bool sse_decode_bool(SseDeserializer deserializer);

  @protected
  Command sse_decode_box_autoadd_command(SseDeserializer deserializer);

  @protected
  LibraryQuery sse_decode_box_autoadd_library_query(
    SseDeserializer deserializer,
  );

  @protected
  TagEdit sse_decode_box_autoadd_tag_edit(SseDeserializer deserializer);

  @protected
  TrackDto sse_decode_box_autoadd_track_dto(SseDeserializer deserializer);

  @protected
  int sse_decode_box_autoadd_u_32(SseDeserializer deserializer);

  @protected
  BridgeFailure sse_decode_bridge_failure(SseDeserializer deserializer);

  @protected
  CatalogDto sse_decode_catalog_dto(SseDeserializer deserializer);

  @protected
  Command sse_decode_command(SseDeserializer deserializer);

  @protected
  ConversionTargetDto sse_decode_conversion_target_dto(
    SseDeserializer deserializer,
  );

  @protected
  double sse_decode_f_32(SseDeserializer deserializer);

  @protected
  double sse_decode_f_64(SseDeserializer deserializer);

  @protected
  FailureKind sse_decode_failure_kind(SseDeserializer deserializer);

  @protected
  FileEntryDto sse_decode_file_entry_dto(SseDeserializer deserializer);

  @protected
  int sse_decode_i_32(SseDeserializer deserializer);

  @protected
  PlatformInt64 sse_decode_i_64(SseDeserializer deserializer);

  @protected
  LibraryPage sse_decode_library_page(SseDeserializer deserializer);

  @protected
  LibraryQuery sse_decode_library_query(SseDeserializer deserializer);

  @protected
  List<String> sse_decode_list_String(SseDeserializer deserializer);

  @protected
  List<ConversionTargetDto> sse_decode_list_conversion_target_dto(
    SseDeserializer deserializer,
  );

  @protected
  List<FileEntryDto> sse_decode_list_file_entry_dto(
    SseDeserializer deserializer,
  );

  @protected
  List<NamedItem> sse_decode_list_named_item(SseDeserializer deserializer);

  @protected
  Float32List sse_decode_list_prim_f_32_strict(SseDeserializer deserializer);

  @protected
  Float64List sse_decode_list_prim_f_64_strict(SseDeserializer deserializer);

  @protected
  Uint8List sse_decode_list_prim_u_8_strict(SseDeserializer deserializer);

  @protected
  List<StationDto> sse_decode_list_station_dto(SseDeserializer deserializer);

  @protected
  List<TrackDto> sse_decode_list_track_dto(SseDeserializer deserializer);

  @protected
  NamedItem sse_decode_named_item(SseDeserializer deserializer);

  @protected
  String? sse_decode_opt_String(SseDeserializer deserializer);

  @protected
  TrackDto? sse_decode_opt_box_autoadd_track_dto(SseDeserializer deserializer);

  @protected
  int? sse_decode_opt_box_autoadd_u_32(SseDeserializer deserializer);

  @protected
  PlaybackDto sse_decode_playback_dto(SseDeserializer deserializer);

  @protected
  PlaybackState sse_decode_playback_state(SseDeserializer deserializer);

  @protected
  PreferencesDto sse_decode_preferences_dto(SseDeserializer deserializer);

  @protected
  SmartView sse_decode_smart_view(SseDeserializer deserializer);

  @protected
  StationDto sse_decode_station_dto(SseDeserializer deserializer);

  @protected
  TagEdit sse_decode_tag_edit(SseDeserializer deserializer);

  @protected
  TrackDto sse_decode_track_dto(SseDeserializer deserializer);

  @protected
  int sse_decode_u_32(SseDeserializer deserializer);

  @protected
  BigInt sse_decode_u_64(SseDeserializer deserializer);

  @protected
  int sse_decode_u_8(SseDeserializer deserializer);

  @protected
  void sse_decode_unit(SseDeserializer deserializer);

  @protected
  BigInt sse_decode_usize(SseDeserializer deserializer);

  @protected
  void
  sse_encode_Auto_Owned_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerSession(
    Session self,
    SseSerializer serializer,
  );

  @protected
  void
  sse_encode_Auto_Ref_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerSession(
    Session self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_CastedPrimitive_i_64(int self, SseSerializer serializer);

  @protected
  void sse_encode_CastedPrimitive_u_64(int self, SseSerializer serializer);

  @protected
  void
  sse_encode_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerSession(
    Session self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_String(String self, SseSerializer serializer);

  @protected
  void sse_encode_bool(bool self, SseSerializer serializer);

  @protected
  void sse_encode_box_autoadd_command(Command self, SseSerializer serializer);

  @protected
  void sse_encode_box_autoadd_library_query(
    LibraryQuery self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_box_autoadd_tag_edit(TagEdit self, SseSerializer serializer);

  @protected
  void sse_encode_box_autoadd_track_dto(
    TrackDto self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_box_autoadd_u_32(int self, SseSerializer serializer);

  @protected
  void sse_encode_bridge_failure(BridgeFailure self, SseSerializer serializer);

  @protected
  void sse_encode_catalog_dto(CatalogDto self, SseSerializer serializer);

  @protected
  void sse_encode_command(Command self, SseSerializer serializer);

  @protected
  void sse_encode_conversion_target_dto(
    ConversionTargetDto self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_f_32(double self, SseSerializer serializer);

  @protected
  void sse_encode_f_64(double self, SseSerializer serializer);

  @protected
  void sse_encode_failure_kind(FailureKind self, SseSerializer serializer);

  @protected
  void sse_encode_file_entry_dto(FileEntryDto self, SseSerializer serializer);

  @protected
  void sse_encode_i_32(int self, SseSerializer serializer);

  @protected
  void sse_encode_i_64(PlatformInt64 self, SseSerializer serializer);

  @protected
  void sse_encode_library_page(LibraryPage self, SseSerializer serializer);

  @protected
  void sse_encode_library_query(LibraryQuery self, SseSerializer serializer);

  @protected
  void sse_encode_list_String(List<String> self, SseSerializer serializer);

  @protected
  void sse_encode_list_conversion_target_dto(
    List<ConversionTargetDto> self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_list_file_entry_dto(
    List<FileEntryDto> self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_list_named_item(
    List<NamedItem> self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_list_prim_f_32_strict(
    Float32List self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_list_prim_f_64_strict(
    Float64List self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_list_prim_u_8_strict(
    Uint8List self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_list_station_dto(
    List<StationDto> self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_list_track_dto(List<TrackDto> self, SseSerializer serializer);

  @protected
  void sse_encode_named_item(NamedItem self, SseSerializer serializer);

  @protected
  void sse_encode_opt_String(String? self, SseSerializer serializer);

  @protected
  void sse_encode_opt_box_autoadd_track_dto(
    TrackDto? self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_opt_box_autoadd_u_32(int? self, SseSerializer serializer);

  @protected
  void sse_encode_playback_dto(PlaybackDto self, SseSerializer serializer);

  @protected
  void sse_encode_playback_state(PlaybackState self, SseSerializer serializer);

  @protected
  void sse_encode_preferences_dto(
    PreferencesDto self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_smart_view(SmartView self, SseSerializer serializer);

  @protected
  void sse_encode_station_dto(StationDto self, SseSerializer serializer);

  @protected
  void sse_encode_tag_edit(TagEdit self, SseSerializer serializer);

  @protected
  void sse_encode_track_dto(TrackDto self, SseSerializer serializer);

  @protected
  void sse_encode_u_32(int self, SseSerializer serializer);

  @protected
  void sse_encode_u_64(BigInt self, SseSerializer serializer);

  @protected
  void sse_encode_u_8(int self, SseSerializer serializer);

  @protected
  void sse_encode_unit(void self, SseSerializer serializer);

  @protected
  void sse_encode_usize(BigInt self, SseSerializer serializer);
}

// Section: wire_class

class RustLibWire implements BaseWire {
  factory RustLibWire.fromExternalLibrary(ExternalLibrary lib) =>
      RustLibWire(lib.ffiDynamicLibrary);

  /// Holds the symbol lookup function.
  final ffi.Pointer<T> Function<T extends ffi.NativeType>(String symbolName)
  _lookup;

  /// The symbols are looked up in [dynamicLibrary].
  RustLibWire(ffi.DynamicLibrary dynamicLibrary)
    : _lookup = dynamicLibrary.lookup;

  void
  rust_arc_increment_strong_count_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerSession(
    ffi.Pointer<ffi.Void> ptr,
  ) {
    return _rust_arc_increment_strong_count_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerSession(
      ptr,
    );
  }

  late final _rust_arc_increment_strong_count_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerSessionPtr =
      _lookup<ffi.NativeFunction<ffi.Void Function(ffi.Pointer<ffi.Void>)>>(
        'frbgen_orange_rust_arc_increment_strong_count_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerSession',
      );
  late final _rust_arc_increment_strong_count_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerSession =
      _rust_arc_increment_strong_count_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerSessionPtr
          .asFunction<void Function(ffi.Pointer<ffi.Void>)>();

  void
  rust_arc_decrement_strong_count_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerSession(
    ffi.Pointer<ffi.Void> ptr,
  ) {
    return _rust_arc_decrement_strong_count_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerSession(
      ptr,
    );
  }

  late final _rust_arc_decrement_strong_count_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerSessionPtr =
      _lookup<ffi.NativeFunction<ffi.Void Function(ffi.Pointer<ffi.Void>)>>(
        'frbgen_orange_rust_arc_decrement_strong_count_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerSession',
      );
  late final _rust_arc_decrement_strong_count_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerSession =
      _rust_arc_decrement_strong_count_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerSessionPtr
          .asFunction<void Function(ffi.Pointer<ffi.Void>)>();
}
