// This file is automatically generated, so please do not edit it.
// @generated by `flutter_rust_bridge`@ 2.13.0.

// ignore_for_file: unused_import, unused_element, unnecessary_import, duplicate_ignore, invalid_use_of_internal_member, annotate_overrides, non_constant_identifier_names, curly_braces_in_flow_control_structures, prefer_const_literals_to_create_immutables, unused_field

import 'api/models.dart';
import 'api/session.dart';

import 'dart:async';
import 'dart:convert';

import 'frb_generated.dart';
import 'frb_generated.io.dart'
    if (dart.library.js_interop) 'frb_generated.web.dart';

import 'package:flutter_rust_bridge/flutter_rust_bridge_for_generated.dart';

/// Main entrypoint of the Rust API
class RustLib extends BaseEntrypoint<RustLibApi, RustLibApiImpl, RustLibWire> {
  @internal
  static final instance = RustLib._();

  RustLib._();

  /// Initialize flutter_rust_bridge
  static Future<void> init({
    RustLibApi? api,
    BaseHandler? handler,
    ExternalLibrary? externalLibrary,
    bool forceSameCodegenVersion = true,
  }) async {
    await instance.initImpl(
      api: api,
      handler: handler,
      externalLibrary: externalLibrary,
      forceSameCodegenVersion: forceSameCodegenVersion,
    );
  }

  /// Initialize flutter_rust_bridge in mock mode.
  /// No libraries for FFI are loaded.
  static void initMock({required RustLibApi api}) {
    instance.initMockImpl(api: api);
  }

  /// Dispose flutter_rust_bridge
  ///
  /// The call to this function is optional, since flutter_rust_bridge (and everything else)
  /// is automatically disposed when the app stops.
  static void dispose() => instance.disposeImpl();

  @override
  ApiImplConstructor<RustLibApiImpl, RustLibWire> get apiImplConstructor =>
      RustLibApiImpl.new;

  @override
  WireConstructor<RustLibWire> get wireConstructor =>
      RustLibWire.fromExternalLibrary;

  @override
  Future<void> executeRustInitializers() async {}

  @override
  ExternalLibraryLoaderConfig get defaultExternalLibraryLoaderConfig =>
      kDefaultExternalLibraryLoaderConfig;

  @override
  String get codegenVersion => '2.13.0';

  @override
  int get rustContentHash => 1432201848;

  static const kDefaultExternalLibraryLoaderConfig =
      ExternalLibraryLoaderConfig(
        stem: 'orange_bridge',
        ioDirectory: '../crates/orange-bridge/target/release/',
        webPrefix: '',
        wasmBindgenName: 'wasm_bindgen',
      );
}

abstract class RustLibApi extends BaseApi {
  Future<CatalogDto> crateApiSessionSessionCatalog({required Session that});

  Future<void> crateApiSessionSessionClose({required Session that});

  Future<void> crateApiSessionSessionDispatch({
    required Session that,
    required Command command,
  });

  Future<PlaybackDto> crateApiSessionSessionPlayback({required Session that});

  Future<LibraryPage> crateApiSessionSessionQueryLibrary({
    required Session that,
    required LibraryQuery query,
  });

  Future<List<TrackDto>> crateApiSessionSessionQueue({required Session that});

  Future<List<ConversionTargetDto>> crateApiSessionConversionTargets();

  Future<LibraryQuery> crateApiModelsLibraryQueryDefault();

  Future<Session> crateApiSessionOpenSession({
    String? profile,
    required List<String> launchUris,
  });

  Future<List<StationDto>> crateApiSessionRadioPresets();

  Future<List<String>> crateApiSessionSupportedAudioExtensions();

  RustArcIncrementStrongCountFnType get rust_arc_increment_strong_count_Session;

  RustArcDecrementStrongCountFnType get rust_arc_decrement_strong_count_Session;

  CrossPlatformFinalizerArg get rust_arc_decrement_strong_count_SessionPtr;
}

class RustLibApiImpl extends RustLibApiImplPlatform implements RustLibApi {
  RustLibApiImpl({
    required super.handler,
    required super.wire,
    required super.generalizedFrbRustBinding,
    required super.portManager,
  });

  @override
  Future<CatalogDto> crateApiSessionSessionCatalog({required Session that}) {
    return handler.executeNormal(
      NormalTask(
        callFfi: (port_) {
          final serializer = SseSerializer(generalizedFrbRustBinding);
          sse_encode_Auto_Ref_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerSession(
            that,
            serializer,
          );
          pdeCallFfi(
            generalizedFrbRustBinding,
            serializer,
            funcId: 1,
            port: port_,
          );
        },
        codec: SseCodec(
          decodeSuccessData: sse_decode_catalog_dto,
          decodeErrorData: sse_decode_bridge_failure,
        ),
        constMeta: kCrateApiSessionSessionCatalogConstMeta,
        argValues: [that],
        apiImpl: this,
      ),
    );
  }

  TaskConstMeta get kCrateApiSessionSessionCatalogConstMeta =>
      const TaskConstMeta(debugName: "Session_catalog", argNames: ["that"]);

  @override
  Future<void> crateApiSessionSessionClose({required Session that}) {
    return handler.executeNormal(
      NormalTask(
        callFfi: (port_) {
          final serializer = SseSerializer(generalizedFrbRustBinding);
          sse_encode_Auto_Ref_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerSession(
            that,
            serializer,
          );
          pdeCallFfi(
            generalizedFrbRustBinding,
            serializer,
            funcId: 2,
            port: port_,
          );
        },
        codec: SseCodec(
          decodeSuccessData: sse_decode_unit,
          decodeErrorData: sse_decode_bridge_failure,
        ),
        constMeta: kCrateApiSessionSessionCloseConstMeta,
        argValues: [that],
        apiImpl: this,
      ),
    );
  }

  TaskConstMeta get kCrateApiSessionSessionCloseConstMeta =>
      const TaskConstMeta(debugName: "Session_close", argNames: ["that"]);

  @override
  Future<void> crateApiSessionSessionDispatch({
    required Session that,
    required Command command,
  }) {
    return handler.executeNormal(
      NormalTask(
        callFfi: (port_) {
          final serializer = SseSerializer(generalizedFrbRustBinding);
          sse_encode_Auto_Ref_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerSession(
            that,
            serializer,
          );
          sse_encode_box_autoadd_command(command, serializer);
          pdeCallFfi(
            generalizedFrbRustBinding,
            serializer,
            funcId: 3,
            port: port_,
          );
        },
        codec: SseCodec(
          decodeSuccessData: sse_decode_unit,
          decodeErrorData: sse_decode_bridge_failure,
        ),
        constMeta: kCrateApiSessionSessionDispatchConstMeta,
        argValues: [that, command],
        apiImpl: this,
      ),
    );
  }

  TaskConstMeta get kCrateApiSessionSessionDispatchConstMeta =>
      const TaskConstMeta(
        debugName: "Session_dispatch",
        argNames: ["that", "command"],
      );

  @override
  Future<PlaybackDto> crateApiSessionSessionPlayback({required Session that}) {
    return handler.executeNormal(
      NormalTask(
        callFfi: (port_) {
          final serializer = SseSerializer(generalizedFrbRustBinding);
          sse_encode_Auto_Ref_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerSession(
            that,
            serializer,
          );
          pdeCallFfi(
            generalizedFrbRustBinding,
            serializer,
            funcId: 4,
            port: port_,
          );
        },
        codec: SseCodec(
          decodeSuccessData: sse_decode_playback_dto,
          decodeErrorData: sse_decode_bridge_failure,
        ),
        constMeta: kCrateApiSessionSessionPlaybackConstMeta,
        argValues: [that],
        apiImpl: this,
      ),
    );
  }

  TaskConstMeta get kCrateApiSessionSessionPlaybackConstMeta =>
      const TaskConstMeta(debugName: "Session_playback", argNames: ["that"]);

  @override
  Future<LibraryPage> crateApiSessionSessionQueryLibrary({
    required Session that,
    required LibraryQuery query,
  }) {
    return handler.executeNormal(
      NormalTask(
        callFfi: (port_) {
          final serializer = SseSerializer(generalizedFrbRustBinding);
          sse_encode_Auto_Ref_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerSession(
            that,
            serializer,
          );
          sse_encode_box_autoadd_library_query(query, serializer);
          pdeCallFfi(
            generalizedFrbRustBinding,
            serializer,
            funcId: 5,
            port: port_,
          );
        },
        codec: SseCodec(
          decodeSuccessData: sse_decode_library_page,
          decodeErrorData: sse_decode_bridge_failure,
        ),
        constMeta: kCrateApiSessionSessionQueryLibraryConstMeta,
        argValues: [that, query],
        apiImpl: this,
      ),
    );
  }

  TaskConstMeta get kCrateApiSessionSessionQueryLibraryConstMeta =>
      const TaskConstMeta(
        debugName: "Session_query_library",
        argNames: ["that", "query"],
      );

  @override
  Future<List<TrackDto>> crateApiSessionSessionQueue({required Session that}) {
    return handler.executeNormal(
      NormalTask(
        callFfi: (port_) {
          final serializer = SseSerializer(generalizedFrbRustBinding);
          sse_encode_Auto_Ref_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerSession(
            that,
            serializer,
          );
          pdeCallFfi(
            generalizedFrbRustBinding,
            serializer,
            funcId: 6,
            port: port_,
          );
        },
        codec: SseCodec(
          decodeSuccessData: sse_decode_list_track_dto,
          decodeErrorData: sse_decode_bridge_failure,
        ),
        constMeta: kCrateApiSessionSessionQueueConstMeta,
        argValues: [that],
        apiImpl: this,
      ),
    );
  }

  TaskConstMeta get kCrateApiSessionSessionQueueConstMeta =>
      const TaskConstMeta(debugName: "Session_queue", argNames: ["that"]);

  @override
  Future<List<ConversionTargetDto>> crateApiSessionConversionTargets() {
    return handler.executeNormal(
      NormalTask(
        callFfi: (port_) {
          final serializer = SseSerializer(generalizedFrbRustBinding);
          pdeCallFfi(
            generalizedFrbRustBinding,
            serializer,
            funcId: 7,
            port: port_,
          );
        },
        codec: SseCodec(
          decodeSuccessData: sse_decode_list_conversion_target_dto,
          decodeErrorData: null,
        ),
        constMeta: kCrateApiSessionConversionTargetsConstMeta,
        argValues: [],
        apiImpl: this,
      ),
    );
  }

  TaskConstMeta get kCrateApiSessionConversionTargetsConstMeta =>
      const TaskConstMeta(debugName: "conversion_targets", argNames: []);

  @override
  Future<LibraryQuery> crateApiModelsLibraryQueryDefault() {
    return handler.executeNormal(
      NormalTask(
        callFfi: (port_) {
          final serializer = SseSerializer(generalizedFrbRustBinding);
          pdeCallFfi(
            generalizedFrbRustBinding,
            serializer,
            funcId: 8,
            port: port_,
          );
        },
        codec: SseCodec(
          decodeSuccessData: sse_decode_library_query,
          decodeErrorData: null,
        ),
        constMeta: kCrateApiModelsLibraryQueryDefaultConstMeta,
        argValues: [],
        apiImpl: this,
      ),
    );
  }

  TaskConstMeta get kCrateApiModelsLibraryQueryDefaultConstMeta =>
      const TaskConstMeta(debugName: "library_query_default", argNames: []);

  @override
  Future<Session> crateApiSessionOpenSession({
    String? profile,
    required List<String> launchUris,
  }) {
    return handler.executeNormal(
      NormalTask(
        callFfi: (port_) {
          final serializer = SseSerializer(generalizedFrbRustBinding);
          sse_encode_opt_String(profile, serializer);
          sse_encode_list_String(launchUris, serializer);
          pdeCallFfi(
            generalizedFrbRustBinding,
            serializer,
            funcId: 9,
            port: port_,
          );
        },
        codec: SseCodec(
          decodeSuccessData:
              sse_decode_Auto_Owned_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerSession,
          decodeErrorData: sse_decode_bridge_failure,
        ),
        constMeta: kCrateApiSessionOpenSessionConstMeta,
        argValues: [profile, launchUris],
        apiImpl: this,
      ),
    );
  }

  TaskConstMeta get kCrateApiSessionOpenSessionConstMeta => const TaskConstMeta(
    debugName: "open_session",
    argNames: ["profile", "launchUris"],
  );

  @override
  Future<List<StationDto>> crateApiSessionRadioPresets() {
    return handler.executeNormal(
      NormalTask(
        callFfi: (port_) {
          final serializer = SseSerializer(generalizedFrbRustBinding);
          pdeCallFfi(
            generalizedFrbRustBinding,
            serializer,
            funcId: 10,
            port: port_,
          );
        },
        codec: SseCodec(
          decodeSuccessData: sse_decode_list_station_dto,
          decodeErrorData: null,
        ),
        constMeta: kCrateApiSessionRadioPresetsConstMeta,
        argValues: [],
        apiImpl: this,
      ),
    );
  }

  TaskConstMeta get kCrateApiSessionRadioPresetsConstMeta =>
      const TaskConstMeta(debugName: "radio_presets", argNames: []);

  @override
  Future<List<String>> crateApiSessionSupportedAudioExtensions() {
    return handler.executeNormal(
      NormalTask(
        callFfi: (port_) {
          final serializer = SseSerializer(generalizedFrbRustBinding);
          pdeCallFfi(
            generalizedFrbRustBinding,
            serializer,
            funcId: 11,
            port: port_,
          );
        },
        codec: SseCodec(
          decodeSuccessData: sse_decode_list_String,
          decodeErrorData: null,
        ),
        constMeta: kCrateApiSessionSupportedAudioExtensionsConstMeta,
        argValues: [],
        apiImpl: this,
      ),
    );
  }

  TaskConstMeta get kCrateApiSessionSupportedAudioExtensionsConstMeta =>
      const TaskConstMeta(
        debugName: "supported_audio_extensions",
        argNames: [],
      );

  RustArcIncrementStrongCountFnType
  get rust_arc_increment_strong_count_Session => wire
      .rust_arc_increment_strong_count_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerSession;

  RustArcDecrementStrongCountFnType
  get rust_arc_decrement_strong_count_Session => wire
      .rust_arc_decrement_strong_count_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerSession;

  @protected
  Session
  dco_decode_Auto_Owned_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerSession(
    dynamic raw,
  ) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return SessionImpl.frbInternalDcoDecode(raw as List<dynamic>);
  }

  @protected
  Session
  dco_decode_Auto_Ref_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerSession(
    dynamic raw,
  ) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return SessionImpl.frbInternalDcoDecode(raw as List<dynamic>);
  }

  @protected
  int dco_decode_CastedPrimitive_i_64(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    throw UnimplementedError(
      'Not implemented in this codec, please use the other one',
    );
  }

  @protected
  int dco_decode_CastedPrimitive_u_64(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    throw UnimplementedError(
      'Not implemented in this codec, please use the other one',
    );
  }

  @protected
  Session
  dco_decode_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerSession(
    dynamic raw,
  ) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return SessionImpl.frbInternalDcoDecode(raw as List<dynamic>);
  }

  @protected
  String dco_decode_String(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return raw as String;
  }

  @protected
  bool dco_decode_bool(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return raw as bool;
  }

  @protected
  Command dco_decode_box_autoadd_command(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return dco_decode_command(raw);
  }

  @protected
  LibraryQuery dco_decode_box_autoadd_library_query(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return dco_decode_library_query(raw);
  }

  @protected
  TagEdit dco_decode_box_autoadd_tag_edit(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return dco_decode_tag_edit(raw);
  }

  @protected
  TrackDto dco_decode_box_autoadd_track_dto(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return dco_decode_track_dto(raw);
  }

  @protected
  int dco_decode_box_autoadd_u_32(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return raw as int;
  }

  @protected
  BridgeFailure dco_decode_bridge_failure(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    final arr = raw as List<dynamic>;
    if (arr.length != 2)
      throw Exception('unexpected arr length: expect 2 but see ${arr.length}');
    return BridgeFailure(
      kind: dco_decode_failure_kind(arr[0]),
      message: dco_decode_String(arr[1]),
    );
  }

  @protected
  CatalogDto dco_decode_catalog_dto(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    final arr = raw as List<dynamic>;
    if (arr.length != 7)
      throw Exception('unexpected arr length: expect 7 but see ${arr.length}');
    return CatalogDto(
      directories: dco_decode_list_named_item(arr[0]),
      playlists: dco_decode_list_named_item(arr[1]),
      stations: dco_decode_list_station_dto(arr[2]),
      radioResults: dco_decode_list_station_dto(arr[3]),
      filesPath: dco_decode_opt_String(arr[4]),
      files: dco_decode_list_file_entry_dto(arr[5]),
      lyrics: dco_decode_opt_String(arr[6]),
    );
  }

  @protected
  Command dco_decode_command(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    switch (raw[0]) {
      case 0:
        return Command_PlayPause();
      case 1:
        return Command_Stop();
      case 2:
        return Command_Next();
      case 3:
        return Command_Previous();
      case 4:
        return Command_StopAfterCurrent();
      case 5:
        return Command_Seek(seconds: dco_decode_u_32(raw[1]));
      case 6:
        return Command_SetVolume(volume: dco_decode_u_8(raw[1]));
      case 7:
        return Command_PlayLibrary(
          query: dco_decode_box_autoadd_library_query(raw[1]),
          index: dco_decode_u_32(raw[2]),
        );
      case 8:
        return Command_Enqueue(urls: dco_decode_list_String(raw[1]));
      case 9:
        return Command_PlayQueue(index: dco_decode_u_32(raw[1]));
      case 10:
        return Command_RemoveQueue(index: dco_decode_u_32(raw[1]));
      case 11:
        return Command_ClearQueue();
      case 12:
        return Command_SetRepeat(mode: dco_decode_u_8(raw[1]));
      case 13:
        return Command_SetShuffle(mode: dco_decode_u_8(raw[1]));
      case 14:
        return Command_SetEqualizer(
          band: dco_decode_u_8(raw[1]),
          gain: dco_decode_f_64(raw[2]),
        );
      case 15:
        return Command_SetTheme(theme: dco_decode_String(raw[1]));
      case 16:
        return Command_SaveWindowSize(
          width: dco_decode_u_32(raw[1]),
          height: dco_decode_u_32(raw[2]),
        );
      case 17:
        return Command_AddFolder(path: dco_decode_String(raw[1]));
      case 18:
        return Command_RemoveFolder(
          id: dco_decode_CastedPrimitive_i_64(raw[1]),
        );
      case 19:
        return Command_Rescan();
      case 20:
        return Command_LoadPlaylist(
          id: dco_decode_CastedPrimitive_i_64(raw[1]),
        );
      case 21:
        return Command_SavePlaylist(name: dco_decode_String(raw[1]));
      case 22:
        return Command_DeletePlaylist(
          id: dco_decode_CastedPrimitive_i_64(raw[1]),
        );
      case 23:
        return Command_OpenFiles(paths: dco_decode_list_String(raw[1]));
      case 24:
        return Command_OpenUris(uris: dco_decode_list_String(raw[1]));
      case 25:
        return Command_PlayFolder(path: dco_decode_String(raw[1]));
      case 26:
        return Command_BrowseFolder(path: dco_decode_String(raw[1]));
      case 27:
        return Command_ExportPlaylist(path: dco_decode_String(raw[1]));
      case 28:
        return Command_ImportPlaylist(path: dco_decode_String(raw[1]));
      case 29:
        return Command_AddStation(
          name: dco_decode_String(raw[1]),
          url: dco_decode_String(raw[2]),
        );
      case 30:
        return Command_RemoveStation(index: dco_decode_u_32(raw[1]));
      case 31:
        return Command_UndoQueue();
      case 32:
        return Command_RedoQueue();
      case 33:
        return Command_SaveTags(edit: dco_decode_box_autoadd_tag_edit(raw[1]));
      case 34:
        return Command_ConvertAudio(
          source: dco_decode_String(raw[1]),
          format: dco_decode_String(raw[2]),
          destination: dco_decode_String(raw[3]),
        );
      case 35:
        return Command_CopyQueue(destination: dco_decode_String(raw[1]));
      case 36:
        return Command_Cancel();
      case 37:
        return Command_SearchRadio(text: dco_decode_String(raw[1]));
      case 38:
        return Command_FetchLyrics();
      case 39:
        return Command_Rate(
          url: dco_decode_String(raw[1]),
          rating: dco_decode_f_64(raw[2]),
        );
      case 40:
        return Command_DismissError();
      default:
        throw Exception("unreachable");
    }
  }

  @protected
  ConversionTargetDto dco_decode_conversion_target_dto(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    final arr = raw as List<dynamic>;
    if (arr.length != 3)
      throw Exception('unexpected arr length: expect 3 but see ${arr.length}');
    return ConversionTargetDto(
      name: dco_decode_String(arr[0]),
      extension_: dco_decode_String(arr[1]),
      available: dco_decode_bool(arr[2]),
    );
  }

  @protected
  double dco_decode_f_32(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return raw as double;
  }

  @protected
  double dco_decode_f_64(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return raw as double;
  }

  @protected
  FailureKind dco_decode_failure_kind(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return FailureKind.values[raw as int];
  }

  @protected
  FileEntryDto dco_decode_file_entry_dto(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    final arr = raw as List<dynamic>;
    if (arr.length != 3)
      throw Exception('unexpected arr length: expect 3 but see ${arr.length}');
    return FileEntryDto(
      name: dco_decode_String(arr[0]),
      path: dco_decode_String(arr[1]),
      directory: dco_decode_bool(arr[2]),
    );
  }

  @protected
  int dco_decode_i_32(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return raw as int;
  }

  @protected
  PlatformInt64 dco_decode_i_64(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return dcoDecodeI64(raw);
  }

  @protected
  LibraryPage dco_decode_library_page(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    final arr = raw as List<dynamic>;
    if (arr.length != 6)
      throw Exception('unexpected arr length: expect 6 but see ${arr.length}');
    return LibraryPage(
      tracks: dco_decode_list_track_dto(arr[0]),
      total: dco_decode_u_32(arr[1]),
      revision: dco_decode_CastedPrimitive_u_64(arr[2]),
      genres: dco_decode_list_String(arr[3]),
      artists: dco_decode_list_String(arr[4]),
      albums: dco_decode_list_String(arr[5]),
    );
  }

  @protected
  LibraryQuery dco_decode_library_query(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    final arr = raw as List<dynamic>;
    if (arr.length != 7)
      throw Exception('unexpected arr length: expect 7 but see ${arr.length}');
    return LibraryQuery(
      text: dco_decode_String(arr[0]),
      genre: dco_decode_String(arr[1]),
      artist: dco_decode_String(arr[2]),
      album: dco_decode_String(arr[3]),
      smart: dco_decode_smart_view(arr[4]),
      offset: dco_decode_u_32(arr[5]),
      limit: dco_decode_u_32(arr[6]),
    );
  }

  @protected
  List<String> dco_decode_list_String(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return (raw as List<dynamic>).map(dco_decode_String).toList();
  }

  @protected
  List<ConversionTargetDto> dco_decode_list_conversion_target_dto(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return (raw as List<dynamic>)
        .map(dco_decode_conversion_target_dto)
        .toList();
  }

  @protected
  List<FileEntryDto> dco_decode_list_file_entry_dto(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return (raw as List<dynamic>).map(dco_decode_file_entry_dto).toList();
  }

  @protected
  List<NamedItem> dco_decode_list_named_item(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return (raw as List<dynamic>).map(dco_decode_named_item).toList();
  }

  @protected
  Float32List dco_decode_list_prim_f_32_strict(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return raw as Float32List;
  }

  @protected
  Float64List dco_decode_list_prim_f_64_strict(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return raw as Float64List;
  }

  @protected
  Uint8List dco_decode_list_prim_u_8_strict(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return raw as Uint8List;
  }

  @protected
  List<StationDto> dco_decode_list_station_dto(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return (raw as List<dynamic>).map(dco_decode_station_dto).toList();
  }

  @protected
  List<TrackDto> dco_decode_list_track_dto(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return (raw as List<dynamic>).map(dco_decode_track_dto).toList();
  }

  @protected
  NamedItem dco_decode_named_item(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    final arr = raw as List<dynamic>;
    if (arr.length != 2)
      throw Exception('unexpected arr length: expect 2 but see ${arr.length}');
    return NamedItem(
      id: dco_decode_CastedPrimitive_i_64(arr[0]),
      name: dco_decode_String(arr[1]),
    );
  }

  @protected
  String? dco_decode_opt_String(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return raw == null ? null : dco_decode_String(raw);
  }

  @protected
  TrackDto? dco_decode_opt_box_autoadd_track_dto(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return raw == null ? null : dco_decode_box_autoadd_track_dto(raw);
  }

  @protected
  int? dco_decode_opt_box_autoadd_u_32(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return raw == null ? null : dco_decode_box_autoadd_u_32(raw);
  }

  @protected
  PlaybackDto dco_decode_playback_dto(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    final arr = raw as List<dynamic>;
    if (arr.length != 17)
      throw Exception('unexpected arr length: expect 17 but see ${arr.length}');
    return PlaybackDto(
      current: dco_decode_opt_box_autoadd_track_dto(arr[0]),
      cursor: dco_decode_opt_box_autoadd_u_32(arr[1]),
      state: dco_decode_playback_state(arr[2]),
      position: dco_decode_u_32(arr[3]),
      duration: dco_decode_u_32(arr[4]),
      spectrum: dco_decode_list_prim_f_32_strict(arr[5]),
      libraryRevision: dco_decode_CastedPrimitive_u_64(arr[6]),
      queueRevision: dco_decode_CastedPrimitive_u_64(arr[7]),
      catalogRevision: dco_decode_CastedPrimitive_u_64(arr[8]),
      preferences: dco_decode_preferences_dto(arr[9]),
      busy: dco_decode_bool(arr[10]),
      canCancel: dco_decode_bool(arr[11]),
      canUndo: dco_decode_bool(arr[12]),
      canRedo: dco_decode_bool(arr[13]),
      status: dco_decode_String(arr[14]),
      error: dco_decode_opt_String(arr[15]),
      shutdown: dco_decode_bool(arr[16]),
    );
  }

  @protected
  PlaybackState dco_decode_playback_state(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return PlaybackState.values[raw as int];
  }

  @protected
  PreferencesDto dco_decode_preferences_dto(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    final arr = raw as List<dynamic>;
    if (arr.length != 7)
      throw Exception('unexpected arr length: expect 7 but see ${arr.length}');
    return PreferencesDto(
      theme: dco_decode_String(arr[0]),
      volume: dco_decode_u_8(arr[1]),
      equalizer: dco_decode_list_prim_f_64_strict(arr[2]),
      repeat: dco_decode_u_8(arr[3]),
      shuffle: dco_decode_u_8(arr[4]),
      windowWidth: dco_decode_u_32(arr[5]),
      windowHeight: dco_decode_u_32(arr[6]),
    );
  }

  @protected
  SmartView dco_decode_smart_view(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return SmartView.values[raw as int];
  }

  @protected
  StationDto dco_decode_station_dto(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    final arr = raw as List<dynamic>;
    if (arr.length != 2)
      throw Exception('unexpected arr length: expect 2 but see ${arr.length}');
    return StationDto(
      name: dco_decode_String(arr[0]),
      url: dco_decode_String(arr[1]),
    );
  }

  @protected
  TagEdit dco_decode_tag_edit(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    final arr = raw as List<dynamic>;
    if (arr.length != 7)
      throw Exception('unexpected arr length: expect 7 but see ${arr.length}');
    return TagEdit(
      path: dco_decode_String(arr[0]),
      title: dco_decode_String(arr[1]),
      artist: dco_decode_String(arr[2]),
      album: dco_decode_String(arr[3]),
      genre: dco_decode_String(arr[4]),
      year: dco_decode_opt_box_autoadd_u_32(arr[5]),
      track: dco_decode_opt_box_autoadd_u_32(arr[6]),
    );
  }

  @protected
  TrackDto dco_decode_track_dto(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    final arr = raw as List<dynamic>;
    if (arr.length != 9)
      throw Exception('unexpected arr length: expect 9 but see ${arr.length}');
    return TrackDto(
      url: dco_decode_String(arr[0]),
      title: dco_decode_String(arr[1]),
      artist: dco_decode_String(arr[2]),
      album: dco_decode_String(arr[3]),
      genre: dco_decode_String(arr[4]),
      year: dco_decode_i_32(arr[5]),
      track: dco_decode_i_32(arr[6]),
      duration: dco_decode_u_32(arr[7]),
      rating: dco_decode_f_64(arr[8]),
    );
  }

  @protected
  int dco_decode_u_32(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return raw as int;
  }

  @protected
  BigInt dco_decode_u_64(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return dcoDecodeU64(raw);
  }

  @protected
  int dco_decode_u_8(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return raw as int;
  }

  @protected
  void dco_decode_unit(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return;
  }

  @protected
  BigInt dco_decode_usize(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return dcoDecodeU64(raw);
  }

  @protected
  Session
  sse_decode_Auto_Owned_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerSession(
    SseDeserializer deserializer,
  ) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    return SessionImpl.frbInternalSseDecode(
      sse_decode_usize(deserializer),
      sse_decode_i_32(deserializer),
    );
  }

  @protected
  Session
  sse_decode_Auto_Ref_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerSession(
    SseDeserializer deserializer,
  ) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    return SessionImpl.frbInternalSseDecode(
      sse_decode_usize(deserializer),
      sse_decode_i_32(deserializer),
    );
  }

  @protected
  int sse_decode_CastedPrimitive_i_64(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    var inner = sse_decode_i_64(deserializer);
    return inner.toInt();
  }

  @protected
  int sse_decode_CastedPrimitive_u_64(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    var inner = sse_decode_u_64(deserializer);
    return inner.toInt();
  }

  @protected
  Session
  sse_decode_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerSession(
    SseDeserializer deserializer,
  ) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    return SessionImpl.frbInternalSseDecode(
      sse_decode_usize(deserializer),
      sse_decode_i_32(deserializer),
    );
  }

  @protected
  String sse_decode_String(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    var inner = sse_decode_list_prim_u_8_strict(deserializer);
    return utf8.decoder.convert(inner);
  }

  @protected
  bool sse_decode_bool(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    return deserializer.buffer.getUint8() != 0;
  }

  @protected
  Command sse_decode_box_autoadd_command(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    return (sse_decode_command(deserializer));
  }

  @protected
  LibraryQuery sse_decode_box_autoadd_library_query(
    SseDeserializer deserializer,
  ) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    return (sse_decode_library_query(deserializer));
  }

  @protected
  TagEdit sse_decode_box_autoadd_tag_edit(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    return (sse_decode_tag_edit(deserializer));
  }

  @protected
  TrackDto sse_decode_box_autoadd_track_dto(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    return (sse_decode_track_dto(deserializer));
  }

  @protected
  int sse_decode_box_autoadd_u_32(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    return (sse_decode_u_32(deserializer));
  }

  @protected
  BridgeFailure sse_decode_bridge_failure(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    var var_kind = sse_decode_failure_kind(deserializer);
    var var_message = sse_decode_String(deserializer);
    return BridgeFailure(kind: var_kind, message: var_message);
  }

  @protected
  CatalogDto sse_decode_catalog_dto(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    var var_directories = sse_decode_list_named_item(deserializer);
    var var_playlists = sse_decode_list_named_item(deserializer);
    var var_stations = sse_decode_list_station_dto(deserializer);
    var var_radioResults = sse_decode_list_station_dto(deserializer);
    var var_filesPath = sse_decode_opt_String(deserializer);
    var var_files = sse_decode_list_file_entry_dto(deserializer);
    var var_lyrics = sse_decode_opt_String(deserializer);
    return CatalogDto(
      directories: var_directories,
      playlists: var_playlists,
      stations: var_stations,
      radioResults: var_radioResults,
      filesPath: var_filesPath,
      files: var_files,
      lyrics: var_lyrics,
    );
  }

  @protected
  Command sse_decode_command(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs

    var tag_ = sse_decode_i_32(deserializer);
    switch (tag_) {
      case 0:
        return Command_PlayPause();
      case 1:
        return Command_Stop();
      case 2:
        return Command_Next();
      case 3:
        return Command_Previous();
      case 4:
        return Command_StopAfterCurrent();
      case 5:
        var var_seconds = sse_decode_u_32(deserializer);
        return Command_Seek(seconds: var_seconds);
      case 6:
        var var_volume = sse_decode_u_8(deserializer);
        return Command_SetVolume(volume: var_volume);
      case 7:
        var var_query = sse_decode_box_autoadd_library_query(deserializer);
        var var_index = sse_decode_u_32(deserializer);
        return Command_PlayLibrary(query: var_query, index: var_index);
      case 8:
        var var_urls = sse_decode_list_String(deserializer);
        return Command_Enqueue(urls: var_urls);
      case 9:
        var var_index = sse_decode_u_32(deserializer);
        return Command_PlayQueue(index: var_index);
      case 10:
        var var_index = sse_decode_u_32(deserializer);
        return Command_RemoveQueue(index: var_index);
      case 11:
        return Command_ClearQueue();
      case 12:
        var var_mode = sse_decode_u_8(deserializer);
        return Command_SetRepeat(mode: var_mode);
      case 13:
        var var_mode = sse_decode_u_8(deserializer);
        return Command_SetShuffle(mode: var_mode);
      case 14:
        var var_band = sse_decode_u_8(deserializer);
        var var_gain = sse_decode_f_64(deserializer);
        return Command_SetEqualizer(band: var_band, gain: var_gain);
      case 15:
        var var_theme = sse_decode_String(deserializer);
        return Command_SetTheme(theme: var_theme);
      case 16:
        var var_width = sse_decode_u_32(deserializer);
        var var_height = sse_decode_u_32(deserializer);
        return Command_SaveWindowSize(width: var_width, height: var_height);
      case 17:
        var var_path = sse_decode_String(deserializer);
        return Command_AddFolder(path: var_path);
      case 18:
        var var_id = sse_decode_CastedPrimitive_i_64(deserializer);
        return Command_RemoveFolder(id: var_id);
      case 19:
        return Command_Rescan();
      case 20:
        var var_id = sse_decode_CastedPrimitive_i_64(deserializer);
        return Command_LoadPlaylist(id: var_id);
      case 21:
        var var_name = sse_decode_String(deserializer);
        return Command_SavePlaylist(name: var_name);
      case 22:
        var var_id = sse_decode_CastedPrimitive_i_64(deserializer);
        return Command_DeletePlaylist(id: var_id);
      case 23:
        var var_paths = sse_decode_list_String(deserializer);
        return Command_OpenFiles(paths: var_paths);
      case 24:
        var var_uris = sse_decode_list_String(deserializer);
        return Command_OpenUris(uris: var_uris);
      case 25:
        var var_path = sse_decode_String(deserializer);
        return Command_PlayFolder(path: var_path);
      case 26:
        var var_path = sse_decode_String(deserializer);
        return Command_BrowseFolder(path: var_path);
      case 27:
        var var_path = sse_decode_String(deserializer);
        return Command_ExportPlaylist(path: var_path);
      case 28:
        var var_path = sse_decode_String(deserializer);
        return Command_ImportPlaylist(path: var_path);
      case 29:
        var var_name = sse_decode_String(deserializer);
        var var_url = sse_decode_String(deserializer);
        return Command_AddStation(name: var_name, url: var_url);
      case 30:
        var var_index = sse_decode_u_32(deserializer);
        return Command_RemoveStation(index: var_index);
      case 31:
        return Command_UndoQueue();
      case 32:
        return Command_RedoQueue();
      case 33:
        var var_edit = sse_decode_box_autoadd_tag_edit(deserializer);
        return Command_SaveTags(edit: var_edit);
      case 34:
        var var_source = sse_decode_String(deserializer);
        var var_format = sse_decode_String(deserializer);
        var var_destination = sse_decode_String(deserializer);
        return Command_ConvertAudio(
          source: var_source,
          format: var_format,
          destination: var_destination,
        );
      case 35:
        var var_destination = sse_decode_String(deserializer);
        return Command_CopyQueue(destination: var_destination);
      case 36:
        return Command_Cancel();
      case 37:
        var var_text = sse_decode_String(deserializer);
        return Command_SearchRadio(text: var_text);
      case 38:
        return Command_FetchLyrics();
      case 39:
        var var_url = sse_decode_String(deserializer);
        var var_rating = sse_decode_f_64(deserializer);
        return Command_Rate(url: var_url, rating: var_rating);
      case 40:
        return Command_DismissError();
      default:
        throw UnimplementedError('');
    }
  }

  @protected
  ConversionTargetDto sse_decode_conversion_target_dto(
    SseDeserializer deserializer,
  ) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    var var_name = sse_decode_String(deserializer);
    var var_extension_ = sse_decode_String(deserializer);
    var var_available = sse_decode_bool(deserializer);
    return ConversionTargetDto(
      name: var_name,
      extension_: var_extension_,
      available: var_available,
    );
  }

  @protected
  double sse_decode_f_32(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    return deserializer.buffer.getFloat32();
  }

  @protected
  double sse_decode_f_64(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    return deserializer.buffer.getFloat64();
  }

  @protected
  FailureKind sse_decode_failure_kind(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    var inner = sse_decode_i_32(deserializer);
    return FailureKind.values[inner];
  }

  @protected
  FileEntryDto sse_decode_file_entry_dto(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    var var_name = sse_decode_String(deserializer);
    var var_path = sse_decode_String(deserializer);
    var var_directory = sse_decode_bool(deserializer);
    return FileEntryDto(
      name: var_name,
      path: var_path,
      directory: var_directory,
    );
  }

  @protected
  int sse_decode_i_32(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    return deserializer.buffer.getInt32();
  }

  @protected
  PlatformInt64 sse_decode_i_64(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    return deserializer.buffer.getPlatformInt64();
  }

  @protected
  LibraryPage sse_decode_library_page(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    var var_tracks = sse_decode_list_track_dto(deserializer);
    var var_total = sse_decode_u_32(deserializer);
    var var_revision = sse_decode_CastedPrimitive_u_64(deserializer);
    var var_genres = sse_decode_list_String(deserializer);
    var var_artists = sse_decode_list_String(deserializer);
    var var_albums = sse_decode_list_String(deserializer);
    return LibraryPage(
      tracks: var_tracks,
      total: var_total,
      revision: var_revision,
      genres: var_genres,
      artists: var_artists,
      albums: var_albums,
    );
  }

  @protected
  LibraryQuery sse_decode_library_query(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    var var_text = sse_decode_String(deserializer);
    var var_genre = sse_decode_String(deserializer);
    var var_artist = sse_decode_String(deserializer);
    var var_album = sse_decode_String(deserializer);
    var var_smart = sse_decode_smart_view(deserializer);
    var var_offset = sse_decode_u_32(deserializer);
    var var_limit = sse_decode_u_32(deserializer);
    return LibraryQuery(
      text: var_text,
      genre: var_genre,
      artist: var_artist,
      album: var_album,
      smart: var_smart,
      offset: var_offset,
      limit: var_limit,
    );
  }

  @protected
  List<String> sse_decode_list_String(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs

    var len_ = sse_decode_i_32(deserializer);
    var ans_ = <String>[];
    for (var idx_ = 0; idx_ < len_; ++idx_) {
      ans_.add(sse_decode_String(deserializer));
    }
    return ans_;
  }

  @protected
  List<ConversionTargetDto> sse_decode_list_conversion_target_dto(
    SseDeserializer deserializer,
  ) {
    // Codec=Sse (Serialization based), see doc to use other codecs

    var len_ = sse_decode_i_32(deserializer);
    var ans_ = <ConversionTargetDto>[];
    for (var idx_ = 0; idx_ < len_; ++idx_) {
      ans_.add(sse_decode_conversion_target_dto(deserializer));
    }
    return ans_;
  }

  @protected
  List<FileEntryDto> sse_decode_list_file_entry_dto(
    SseDeserializer deserializer,
  ) {
    // Codec=Sse (Serialization based), see doc to use other codecs

    var len_ = sse_decode_i_32(deserializer);
    var ans_ = <FileEntryDto>[];
    for (var idx_ = 0; idx_ < len_; ++idx_) {
      ans_.add(sse_decode_file_entry_dto(deserializer));
    }
    return ans_;
  }

  @protected
  List<NamedItem> sse_decode_list_named_item(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs

    var len_ = sse_decode_i_32(deserializer);
    var ans_ = <NamedItem>[];
    for (var idx_ = 0; idx_ < len_; ++idx_) {
      ans_.add(sse_decode_named_item(deserializer));
    }
    return ans_;
  }

  @protected
  Float32List sse_decode_list_prim_f_32_strict(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    var len_ = sse_decode_i_32(deserializer);
    return deserializer.buffer.getFloat32List(len_);
  }

  @protected
  Float64List sse_decode_list_prim_f_64_strict(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    var len_ = sse_decode_i_32(deserializer);
    return deserializer.buffer.getFloat64List(len_);
  }

  @protected
  Uint8List sse_decode_list_prim_u_8_strict(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    var len_ = sse_decode_i_32(deserializer);
    return deserializer.buffer.getUint8List(len_);
  }

  @protected
  List<StationDto> sse_decode_list_station_dto(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs

    var len_ = sse_decode_i_32(deserializer);
    var ans_ = <StationDto>[];
    for (var idx_ = 0; idx_ < len_; ++idx_) {
      ans_.add(sse_decode_station_dto(deserializer));
    }
    return ans_;
  }

  @protected
  List<TrackDto> sse_decode_list_track_dto(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs

    var len_ = sse_decode_i_32(deserializer);
    var ans_ = <TrackDto>[];
    for (var idx_ = 0; idx_ < len_; ++idx_) {
      ans_.add(sse_decode_track_dto(deserializer));
    }
    return ans_;
  }

  @protected
  NamedItem sse_decode_named_item(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    var var_id = sse_decode_CastedPrimitive_i_64(deserializer);
    var var_name = sse_decode_String(deserializer);
    return NamedItem(id: var_id, name: var_name);
  }

  @protected
  String? sse_decode_opt_String(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs

    if (sse_decode_bool(deserializer)) {
      return (sse_decode_String(deserializer));
    } else {
      return null;
    }
  }

  @protected
  TrackDto? sse_decode_opt_box_autoadd_track_dto(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs

    if (sse_decode_bool(deserializer)) {
      return (sse_decode_box_autoadd_track_dto(deserializer));
    } else {
      return null;
    }
  }

  @protected
  int? sse_decode_opt_box_autoadd_u_32(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs

    if (sse_decode_bool(deserializer)) {
      return (sse_decode_box_autoadd_u_32(deserializer));
    } else {
      return null;
    }
  }

  @protected
  PlaybackDto sse_decode_playback_dto(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    var var_current = sse_decode_opt_box_autoadd_track_dto(deserializer);
    var var_cursor = sse_decode_opt_box_autoadd_u_32(deserializer);
    var var_state = sse_decode_playback_state(deserializer);
    var var_position = sse_decode_u_32(deserializer);
    var var_duration = sse_decode_u_32(deserializer);
    var var_spectrum = sse_decode_list_prim_f_32_strict(deserializer);
    var var_libraryRevision = sse_decode_CastedPrimitive_u_64(deserializer);
    var var_queueRevision = sse_decode_CastedPrimitive_u_64(deserializer);
    var var_catalogRevision = sse_decode_CastedPrimitive_u_64(deserializer);
    var var_preferences = sse_decode_preferences_dto(deserializer);
    var var_busy = sse_decode_bool(deserializer);
    var var_canCancel = sse_decode_bool(deserializer);
    var var_canUndo = sse_decode_bool(deserializer);
    var var_canRedo = sse_decode_bool(deserializer);
    var var_status = sse_decode_String(deserializer);
    var var_error = sse_decode_opt_String(deserializer);
    var var_shutdown = sse_decode_bool(deserializer);
    return PlaybackDto(
      current: var_current,
      cursor: var_cursor,
      state: var_state,
      position: var_position,
      duration: var_duration,
      spectrum: var_spectrum,
      libraryRevision: var_libraryRevision,
      queueRevision: var_queueRevision,
      catalogRevision: var_catalogRevision,
      preferences: var_preferences,
      busy: var_busy,
      canCancel: var_canCancel,
      canUndo: var_canUndo,
      canRedo: var_canRedo,
      status: var_status,
      error: var_error,
      shutdown: var_shutdown,
    );
  }

  @protected
  PlaybackState sse_decode_playback_state(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    var inner = sse_decode_i_32(deserializer);
    return PlaybackState.values[inner];
  }

  @protected
  PreferencesDto sse_decode_preferences_dto(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    var var_theme = sse_decode_String(deserializer);
    var var_volume = sse_decode_u_8(deserializer);
    var var_equalizer = sse_decode_list_prim_f_64_strict(deserializer);
    var var_repeat = sse_decode_u_8(deserializer);
    var var_shuffle = sse_decode_u_8(deserializer);
    var var_windowWidth = sse_decode_u_32(deserializer);
    var var_windowHeight = sse_decode_u_32(deserializer);
    return PreferencesDto(
      theme: var_theme,
      volume: var_volume,
      equalizer: var_equalizer,
      repeat: var_repeat,
      shuffle: var_shuffle,
      windowWidth: var_windowWidth,
      windowHeight: var_windowHeight,
    );
  }

  @protected
  SmartView sse_decode_smart_view(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    var inner = sse_decode_i_32(deserializer);
    return SmartView.values[inner];
  }

  @protected
  StationDto sse_decode_station_dto(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    var var_name = sse_decode_String(deserializer);
    var var_url = sse_decode_String(deserializer);
    return StationDto(name: var_name, url: var_url);
  }

  @protected
  TagEdit sse_decode_tag_edit(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    var var_path = sse_decode_String(deserializer);
    var var_title = sse_decode_String(deserializer);
    var var_artist = sse_decode_String(deserializer);
    var var_album = sse_decode_String(deserializer);
    var var_genre = sse_decode_String(deserializer);
    var var_year = sse_decode_opt_box_autoadd_u_32(deserializer);
    var var_track = sse_decode_opt_box_autoadd_u_32(deserializer);
    return TagEdit(
      path: var_path,
      title: var_title,
      artist: var_artist,
      album: var_album,
      genre: var_genre,
      year: var_year,
      track: var_track,
    );
  }

  @protected
  TrackDto sse_decode_track_dto(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    var var_url = sse_decode_String(deserializer);
    var var_title = sse_decode_String(deserializer);
    var var_artist = sse_decode_String(deserializer);
    var var_album = sse_decode_String(deserializer);
    var var_genre = sse_decode_String(deserializer);
    var var_year = sse_decode_i_32(deserializer);
    var var_track = sse_decode_i_32(deserializer);
    var var_duration = sse_decode_u_32(deserializer);
    var var_rating = sse_decode_f_64(deserializer);
    return TrackDto(
      url: var_url,
      title: var_title,
      artist: var_artist,
      album: var_album,
      genre: var_genre,
      year: var_year,
      track: var_track,
      duration: var_duration,
      rating: var_rating,
    );
  }

  @protected
  int sse_decode_u_32(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    return deserializer.buffer.getUint32();
  }

  @protected
  BigInt sse_decode_u_64(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    return deserializer.buffer.getBigUint64();
  }

  @protected
  int sse_decode_u_8(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    return deserializer.buffer.getUint8();
  }

  @protected
  void sse_decode_unit(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
  }

  @protected
  BigInt sse_decode_usize(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    return deserializer.buffer.getBigUint64();
  }

  @protected
  void
  sse_encode_Auto_Owned_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerSession(
    Session self,
    SseSerializer serializer,
  ) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_usize(
      (self as SessionImpl).frbInternalSseEncode(move: true),
      serializer,
    );
  }

  @protected
  void
  sse_encode_Auto_Ref_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerSession(
    Session self,
    SseSerializer serializer,
  ) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_usize(
      (self as SessionImpl).frbInternalSseEncode(move: false),
      serializer,
    );
  }

  @protected
  void sse_encode_CastedPrimitive_i_64(int self, SseSerializer serializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_i_64(sseEncodeCastedPrimitiveI64(self), serializer);
  }

  @protected
  void sse_encode_CastedPrimitive_u_64(int self, SseSerializer serializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_u_64(sseEncodeCastedPrimitiveU64(self), serializer);
  }

  @protected
  void
  sse_encode_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerSession(
    Session self,
    SseSerializer serializer,
  ) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_usize(
      (self as SessionImpl).frbInternalSseEncode(move: null),
      serializer,
    );
  }

  @protected
  void sse_encode_String(String self, SseSerializer serializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_list_prim_u_8_strict(utf8.encoder.convert(self), serializer);
  }

  @protected
  void sse_encode_bool(bool self, SseSerializer serializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    serializer.buffer.putUint8(self ? 1 : 0);
  }

  @protected
  void sse_encode_box_autoadd_command(Command self, SseSerializer serializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_command(self, serializer);
  }

  @protected
  void sse_encode_box_autoadd_library_query(
    LibraryQuery self,
    SseSerializer serializer,
  ) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_library_query(self, serializer);
  }

  @protected
  void sse_encode_box_autoadd_tag_edit(TagEdit self, SseSerializer serializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_tag_edit(self, serializer);
  }

  @protected
  void sse_encode_box_autoadd_track_dto(
    TrackDto self,
    SseSerializer serializer,
  ) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_track_dto(self, serializer);
  }

  @protected
  void sse_encode_box_autoadd_u_32(int self, SseSerializer serializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_u_32(self, serializer);
  }

  @protected
  void sse_encode_bridge_failure(BridgeFailure self, SseSerializer serializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_failure_kind(self.kind, serializer);
    sse_encode_String(self.message, serializer);
  }

  @protected
  void sse_encode_catalog_dto(CatalogDto self, SseSerializer serializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_list_named_item(self.directories, serializer);
    sse_encode_list_named_item(self.playlists, serializer);
    sse_encode_list_station_dto(self.stations, serializer);
    sse_encode_list_station_dto(self.radioResults, serializer);
    sse_encode_opt_String(self.filesPath, serializer);
    sse_encode_list_file_entry_dto(self.files, serializer);
    sse_encode_opt_String(self.lyrics, serializer);
  }

  @protected
  void sse_encode_command(Command self, SseSerializer serializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    switch (self) {
      case Command_PlayPause():
        sse_encode_i_32(0, serializer);
      case Command_Stop():
        sse_encode_i_32(1, serializer);
      case Command_Next():
        sse_encode_i_32(2, serializer);
      case Command_Previous():
        sse_encode_i_32(3, serializer);
      case Command_StopAfterCurrent():
        sse_encode_i_32(4, serializer);
      case Command_Seek(seconds: final seconds):
        sse_encode_i_32(5, serializer);
        sse_encode_u_32(seconds, serializer);
      case Command_SetVolume(volume: final volume):
        sse_encode_i_32(6, serializer);
        sse_encode_u_8(volume, serializer);
      case Command_PlayLibrary(query: final query, index: final index):
        sse_encode_i_32(7, serializer);
        sse_encode_box_autoadd_library_query(query, serializer);
        sse_encode_u_32(index, serializer);
      case Command_Enqueue(urls: final urls):
        sse_encode_i_32(8, serializer);
        sse_encode_list_String(urls, serializer);
      case Command_PlayQueue(index: final index):
        sse_encode_i_32(9, serializer);
        sse_encode_u_32(index, serializer);
      case Command_RemoveQueue(index: final index):
        sse_encode_i_32(10, serializer);
        sse_encode_u_32(index, serializer);
      case Command_ClearQueue():
        sse_encode_i_32(11, serializer);
      case Command_SetRepeat(mode: final mode):
        sse_encode_i_32(12, serializer);
        sse_encode_u_8(mode, serializer);
      case Command_SetShuffle(mode: final mode):
        sse_encode_i_32(13, serializer);
        sse_encode_u_8(mode, serializer);
      case Command_SetEqualizer(band: final band, gain: final gain):
        sse_encode_i_32(14, serializer);
        sse_encode_u_8(band, serializer);
        sse_encode_f_64(gain, serializer);
      case Command_SetTheme(theme: final theme):
        sse_encode_i_32(15, serializer);
        sse_encode_String(theme, serializer);
      case Command_SaveWindowSize(width: final width, height: final height):
        sse_encode_i_32(16, serializer);
        sse_encode_u_32(width, serializer);
        sse_encode_u_32(height, serializer);
      case Command_AddFolder(path: final path):
        sse_encode_i_32(17, serializer);
        sse_encode_String(path, serializer);
      case Command_RemoveFolder(id: final id):
        sse_encode_i_32(18, serializer);
        sse_encode_CastedPrimitive_i_64(id, serializer);
      case Command_Rescan():
        sse_encode_i_32(19, serializer);
      case Command_LoadPlaylist(id: final id):
        sse_encode_i_32(20, serializer);
        sse_encode_CastedPrimitive_i_64(id, serializer);
      case Command_SavePlaylist(name: final name):
        sse_encode_i_32(21, serializer);
        sse_encode_String(name, serializer);
      case Command_DeletePlaylist(id: final id):
        sse_encode_i_32(22, serializer);
        sse_encode_CastedPrimitive_i_64(id, serializer);
      case Command_OpenFiles(paths: final paths):
        sse_encode_i_32(23, serializer);
        sse_encode_list_String(paths, serializer);
      case Command_OpenUris(uris: final uris):
        sse_encode_i_32(24, serializer);
        sse_encode_list_String(uris, serializer);
      case Command_PlayFolder(path: final path):
        sse_encode_i_32(25, serializer);
        sse_encode_String(path, serializer);
      case Command_BrowseFolder(path: final path):
        sse_encode_i_32(26, serializer);
        sse_encode_String(path, serializer);
      case Command_ExportPlaylist(path: final path):
        sse_encode_i_32(27, serializer);
        sse_encode_String(path, serializer);
      case Command_ImportPlaylist(path: final path):
        sse_encode_i_32(28, serializer);
        sse_encode_String(path, serializer);
      case Command_AddStation(name: final name, url: final url):
        sse_encode_i_32(29, serializer);
        sse_encode_String(name, serializer);
        sse_encode_String(url, serializer);
      case Command_RemoveStation(index: final index):
        sse_encode_i_32(30, serializer);
        sse_encode_u_32(index, serializer);
      case Command_UndoQueue():
        sse_encode_i_32(31, serializer);
      case Command_RedoQueue():
        sse_encode_i_32(32, serializer);
      case Command_SaveTags(edit: final edit):
        sse_encode_i_32(33, serializer);
        sse_encode_box_autoadd_tag_edit(edit, serializer);
      case Command_ConvertAudio(
        source: final source,
        format: final format,
        destination: final destination,
      ):
        sse_encode_i_32(34, serializer);
        sse_encode_String(source, serializer);
        sse_encode_String(format, serializer);
        sse_encode_String(destination, serializer);
      case Command_CopyQueue(destination: final destination):
        sse_encode_i_32(35, serializer);
        sse_encode_String(destination, serializer);
      case Command_Cancel():
        sse_encode_i_32(36, serializer);
      case Command_SearchRadio(text: final text):
        sse_encode_i_32(37, serializer);
        sse_encode_String(text, serializer);
      case Command_FetchLyrics():
        sse_encode_i_32(38, serializer);
      case Command_Rate(url: final url, rating: final rating):
        sse_encode_i_32(39, serializer);
        sse_encode_String(url, serializer);
        sse_encode_f_64(rating, serializer);
      case Command_DismissError():
        sse_encode_i_32(40, serializer);
    }
  }

  @protected
  void sse_encode_conversion_target_dto(
    ConversionTargetDto self,
    SseSerializer serializer,
  ) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_String(self.name, serializer);
    sse_encode_String(self.extension_, serializer);
    sse_encode_bool(self.available, serializer);
  }

  @protected
  void sse_encode_f_32(double self, SseSerializer serializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    serializer.buffer.putFloat32(self);
  }

  @protected
  void sse_encode_f_64(double self, SseSerializer serializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    serializer.buffer.putFloat64(self);
  }

  @protected
  void sse_encode_failure_kind(FailureKind self, SseSerializer serializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_i_32(self.index, serializer);
  }

  @protected
  void sse_encode_file_entry_dto(FileEntryDto self, SseSerializer serializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_String(self.name, serializer);
    sse_encode_String(self.path, serializer);
    sse_encode_bool(self.directory, serializer);
  }

  @protected
  void sse_encode_i_32(int self, SseSerializer serializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    serializer.buffer.putInt32(self);
  }

  @protected
  void sse_encode_i_64(PlatformInt64 self, SseSerializer serializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    serializer.buffer.putPlatformInt64(self);
  }

  @protected
  void sse_encode_library_page(LibraryPage self, SseSerializer serializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_list_track_dto(self.tracks, serializer);
    sse_encode_u_32(self.total, serializer);
    sse_encode_CastedPrimitive_u_64(self.revision, serializer);
    sse_encode_list_String(self.genres, serializer);
    sse_encode_list_String(self.artists, serializer);
    sse_encode_list_String(self.albums, serializer);
  }

  @protected
  void sse_encode_library_query(LibraryQuery self, SseSerializer serializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_String(self.text, serializer);
    sse_encode_String(self.genre, serializer);
    sse_encode_String(self.artist, serializer);
    sse_encode_String(self.album, serializer);
    sse_encode_smart_view(self.smart, serializer);
    sse_encode_u_32(self.offset, serializer);
    sse_encode_u_32(self.limit, serializer);
  }

  @protected
  void sse_encode_list_String(List<String> self, SseSerializer serializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_i_32(self.length, serializer);
    for (final item in self) {
      sse_encode_String(item, serializer);
    }
  }

  @protected
  void sse_encode_list_conversion_target_dto(
    List<ConversionTargetDto> self,
    SseSerializer serializer,
  ) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_i_32(self.length, serializer);
    for (final item in self) {
      sse_encode_conversion_target_dto(item, serializer);
    }
  }

  @protected
  void sse_encode_list_file_entry_dto(
    List<FileEntryDto> self,
    SseSerializer serializer,
  ) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_i_32(self.length, serializer);
    for (final item in self) {
      sse_encode_file_entry_dto(item, serializer);
    }
  }

  @protected
  void sse_encode_list_named_item(
    List<NamedItem> self,
    SseSerializer serializer,
  ) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_i_32(self.length, serializer);
    for (final item in self) {
      sse_encode_named_item(item, serializer);
    }
  }

  @protected
  void sse_encode_list_prim_f_32_strict(
    Float32List self,
    SseSerializer serializer,
  ) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_i_32(self.length, serializer);
    serializer.buffer.putFloat32List(self);
  }

  @protected
  void sse_encode_list_prim_f_64_strict(
    Float64List self,
    SseSerializer serializer,
  ) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_i_32(self.length, serializer);
    serializer.buffer.putFloat64List(self);
  }

  @protected
  void sse_encode_list_prim_u_8_strict(
    Uint8List self,
    SseSerializer serializer,
  ) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_i_32(self.length, serializer);
    serializer.buffer.putUint8List(self);
  }

  @protected
  void sse_encode_list_station_dto(
    List<StationDto> self,
    SseSerializer serializer,
  ) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_i_32(self.length, serializer);
    for (final item in self) {
      sse_encode_station_dto(item, serializer);
    }
  }

  @protected
  void sse_encode_list_track_dto(
    List<TrackDto> self,
    SseSerializer serializer,
  ) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_i_32(self.length, serializer);
    for (final item in self) {
      sse_encode_track_dto(item, serializer);
    }
  }

  @protected
  void sse_encode_named_item(NamedItem self, SseSerializer serializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_CastedPrimitive_i_64(self.id, serializer);
    sse_encode_String(self.name, serializer);
  }

  @protected
  void sse_encode_opt_String(String? self, SseSerializer serializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs

    sse_encode_bool(self != null, serializer);
    if (self != null) {
      sse_encode_String(self, serializer);
    }
  }

  @protected
  void sse_encode_opt_box_autoadd_track_dto(
    TrackDto? self,
    SseSerializer serializer,
  ) {
    // Codec=Sse (Serialization based), see doc to use other codecs

    sse_encode_bool(self != null, serializer);
    if (self != null) {
      sse_encode_box_autoadd_track_dto(self, serializer);
    }
  }

  @protected
  void sse_encode_opt_box_autoadd_u_32(int? self, SseSerializer serializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs

    sse_encode_bool(self != null, serializer);
    if (self != null) {
      sse_encode_box_autoadd_u_32(self, serializer);
    }
  }

  @protected
  void sse_encode_playback_dto(PlaybackDto self, SseSerializer serializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_opt_box_autoadd_track_dto(self.current, serializer);
    sse_encode_opt_box_autoadd_u_32(self.cursor, serializer);
    sse_encode_playback_state(self.state, serializer);
    sse_encode_u_32(self.position, serializer);
    sse_encode_u_32(self.duration, serializer);
    sse_encode_list_prim_f_32_strict(self.spectrum, serializer);
    sse_encode_CastedPrimitive_u_64(self.libraryRevision, serializer);
    sse_encode_CastedPrimitive_u_64(self.queueRevision, serializer);
    sse_encode_CastedPrimitive_u_64(self.catalogRevision, serializer);
    sse_encode_preferences_dto(self.preferences, serializer);
    sse_encode_bool(self.busy, serializer);
    sse_encode_bool(self.canCancel, serializer);
    sse_encode_bool(self.canUndo, serializer);
    sse_encode_bool(self.canRedo, serializer);
    sse_encode_String(self.status, serializer);
    sse_encode_opt_String(self.error, serializer);
    sse_encode_bool(self.shutdown, serializer);
  }

  @protected
  void sse_encode_playback_state(PlaybackState self, SseSerializer serializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_i_32(self.index, serializer);
  }

  @protected
  void sse_encode_preferences_dto(
    PreferencesDto self,
    SseSerializer serializer,
  ) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_String(self.theme, serializer);
    sse_encode_u_8(self.volume, serializer);
    sse_encode_list_prim_f_64_strict(self.equalizer, serializer);
    sse_encode_u_8(self.repeat, serializer);
    sse_encode_u_8(self.shuffle, serializer);
    sse_encode_u_32(self.windowWidth, serializer);
    sse_encode_u_32(self.windowHeight, serializer);
  }

  @protected
  void sse_encode_smart_view(SmartView self, SseSerializer serializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_i_32(self.index, serializer);
  }

  @protected
  void sse_encode_station_dto(StationDto self, SseSerializer serializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_String(self.name, serializer);
    sse_encode_String(self.url, serializer);
  }

  @protected
  void sse_encode_tag_edit(TagEdit self, SseSerializer serializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_String(self.path, serializer);
    sse_encode_String(self.title, serializer);
    sse_encode_String(self.artist, serializer);
    sse_encode_String(self.album, serializer);
    sse_encode_String(self.genre, serializer);
    sse_encode_opt_box_autoadd_u_32(self.year, serializer);
    sse_encode_opt_box_autoadd_u_32(self.track, serializer);
  }

  @protected
  void sse_encode_track_dto(TrackDto self, SseSerializer serializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_String(self.url, serializer);
    sse_encode_String(self.title, serializer);
    sse_encode_String(self.artist, serializer);
    sse_encode_String(self.album, serializer);
    sse_encode_String(self.genre, serializer);
    sse_encode_i_32(self.year, serializer);
    sse_encode_i_32(self.track, serializer);
    sse_encode_u_32(self.duration, serializer);
    sse_encode_f_64(self.rating, serializer);
  }

  @protected
  void sse_encode_u_32(int self, SseSerializer serializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    serializer.buffer.putUint32(self);
  }

  @protected
  void sse_encode_u_64(BigInt self, SseSerializer serializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    serializer.buffer.putBigUint64(self);
  }

  @protected
  void sse_encode_u_8(int self, SseSerializer serializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    serializer.buffer.putUint8(self);
  }

  @protected
  void sse_encode_unit(void self, SseSerializer serializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
  }

  @protected
  void sse_encode_usize(BigInt self, SseSerializer serializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    serializer.buffer.putBigUint64(self);
  }
}

@sealed
class SessionImpl extends RustOpaque implements Session {
  // Not to be used by end users
  SessionImpl.frbInternalDcoDecode(List<dynamic> wire)
    : super.frbInternalDcoDecode(wire, _kStaticData);

  // Not to be used by end users
  SessionImpl.frbInternalSseDecode(BigInt ptr, int externalSizeOnNative)
    : super.frbInternalSseDecode(ptr, externalSizeOnNative, _kStaticData);

  static final _kStaticData = RustArcStaticData(
    rustArcIncrementStrongCount:
        RustLib.instance.api.rust_arc_increment_strong_count_Session,
    rustArcDecrementStrongCount:
        RustLib.instance.api.rust_arc_decrement_strong_count_Session,
    rustArcDecrementStrongCountPtr:
        RustLib.instance.api.rust_arc_decrement_strong_count_SessionPtr,
  );

  Future<CatalogDto> catalog() =>
      RustLib.instance.api.crateApiSessionSessionCatalog(that: this);

  Future<void> close() =>
      RustLib.instance.api.crateApiSessionSessionClose(that: this);

  /// A shared command path for menus, keyboard actions and rendered controls.
  Future<void> dispatch({required Command command}) => RustLib.instance.api
      .crateApiSessionSessionDispatch(that: this, command: command);

  /// Small playback/preferences updates; library and queue rows stay separate.
  Future<PlaybackDto> playback() =>
      RustLib.instance.api.crateApiSessionSessionPlayback(that: this);

  Future<LibraryPage> queryLibrary({required LibraryQuery query}) => RustLib
      .instance
      .api
      .crateApiSessionSessionQueryLibrary(that: this, query: query);

  Future<List<TrackDto>> queue() =>
      RustLib.instance.api.crateApiSessionSessionQueue(that: this);
}
