// This file is automatically generated, so please do not edit it.
// @generated by `flutter_rust_bridge`@ 2.13.0.

// ignore_for_file: invalid_use_of_internal_member, unused_import, unnecessary_import

import '../frb_generated.dart';

import 'package:flutter_rust_bridge/flutter_rust_bridge_for_generated.dart';
import 'package:freezed_annotation/freezed_annotation.dart' hide protected;
part 'models.freezed.dart';

// These functions are ignored because they are not marked as `pub`: `new`
// These function are ignored because they are on traits that is not defined in current crate (put an empty `#[frb]` on it to unignore): `assert_fields_are_eq`, `assert_fields_are_eq`, `assert_fields_are_eq`, `clone`, `clone`, `clone`, `clone`, `clone`, `clone`, `clone`, `clone`, `clone`, `clone`, `clone`, `clone`, `clone`, `clone`, `clone`, `clone`, `eq`, `eq`, `eq`, `fmt`, `fmt`, `fmt`, `fmt`, `fmt`, `fmt`, `fmt`, `fmt`, `fmt`, `fmt`, `fmt`, `fmt`, `fmt`, `fmt`, `fmt`, `fmt`, `fmt`

class BridgeFailure implements FrbException {
  final FailureKind kind;
  final String message;

  const BridgeFailure({required this.kind, required this.message});

  @override
  int get hashCode => kind.hashCode ^ message.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is BridgeFailure &&
          runtimeType == other.runtimeType &&
          kind == other.kind &&
          message == other.message;
}

class CatalogDto {
  final List<NamedItem> directories;
  final List<NamedItem> playlists;
  final List<StationDto> stations;
  final List<StationDto> radioResults;
  final String? filesPath;
  final List<FileEntryDto> files;
  final String? lyrics;

  const CatalogDto({
    required this.directories,
    required this.playlists,
    required this.stations,
    required this.radioResults,
    this.filesPath,
    required this.files,
    this.lyrics,
  });

  @override
  int get hashCode =>
      directories.hashCode ^
      playlists.hashCode ^
      stations.hashCode ^
      radioResults.hashCode ^
      filesPath.hashCode ^
      files.hashCode ^
      lyrics.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is CatalogDto &&
          runtimeType == other.runtimeType &&
          directories == other.directories &&
          playlists == other.playlists &&
          stations == other.stations &&
          radioResults == other.radioResults &&
          filesPath == other.filesPath &&
          files == other.files &&
          lyrics == other.lyrics;
}

@freezed
sealed class Command with _$Command {
  const Command._();

  const factory Command.playPause() = Command_PlayPause;
  const factory Command.stop() = Command_Stop;
  const factory Command.next() = Command_Next;
  const factory Command.previous() = Command_Previous;
  const factory Command.stopAfterCurrent() = Command_StopAfterCurrent;
  const factory Command.seek({required int seconds}) = Command_Seek;
  const factory Command.setVolume({required int volume}) = Command_SetVolume;
  const factory Command.playLibrary({
    required LibraryQuery query,
    required int index,
  }) = Command_PlayLibrary;
  const factory Command.enqueue({required List<String> urls}) = Command_Enqueue;
  const factory Command.playQueue({required int index}) = Command_PlayQueue;
  const factory Command.removeQueue({required int index}) = Command_RemoveQueue;
  const factory Command.clearQueue() = Command_ClearQueue;
  const factory Command.setRepeat({required int mode}) = Command_SetRepeat;
  const factory Command.setShuffle({required int mode}) = Command_SetShuffle;
  const factory Command.setEqualizer({
    required int band,
    required double gain,
  }) = Command_SetEqualizer;
  const factory Command.setTheme({required String theme}) = Command_SetTheme;
  const factory Command.saveWindowSize({
    required int width,
    required int height,
  }) = Command_SaveWindowSize;
  const factory Command.addFolder({required String path}) = Command_AddFolder;
  const factory Command.removeFolder({required int id}) = Command_RemoveFolder;
  const factory Command.rescan() = Command_Rescan;
  const factory Command.loadPlaylist({required int id}) = Command_LoadPlaylist;
  const factory Command.savePlaylist({required String name}) =
      Command_SavePlaylist;
  const factory Command.deletePlaylist({required int id}) =
      Command_DeletePlaylist;
  const factory Command.openFiles({required List<String> paths}) =
      Command_OpenFiles;
  const factory Command.openUris({required List<String> uris}) =
      Command_OpenUris;
  const factory Command.playFolder({required String path}) = Command_PlayFolder;
  const factory Command.browseFolder({required String path}) =
      Command_BrowseFolder;
  const factory Command.exportPlaylist({required String path}) =
      Command_ExportPlaylist;
  const factory Command.importPlaylist({required String path}) =
      Command_ImportPlaylist;
  const factory Command.addStation({
    required String name,
    required String url,
  }) = Command_AddStation;
  const factory Command.removeStation({required int index}) =
      Command_RemoveStation;
  const factory Command.undoQueue() = Command_UndoQueue;
  const factory Command.redoQueue() = Command_RedoQueue;
  const factory Command.saveTags({required TagEdit edit}) = Command_SaveTags;
  const factory Command.convertAudio({
    required String source,
    required String format,
    required String destination,
  }) = Command_ConvertAudio;
  const factory Command.copyQueue({required String destination}) =
      Command_CopyQueue;
  const factory Command.cancel() = Command_Cancel;
  const factory Command.searchRadio({required String text}) =
      Command_SearchRadio;
  const factory Command.fetchLyrics() = Command_FetchLyrics;
  const factory Command.rate({required String url, required double rating}) =
      Command_Rate;
  const factory Command.dismissError() = Command_DismissError;
}

class ConversionTargetDto {
  final String name;
  final String extension_;
  final bool available;

  const ConversionTargetDto({
    required this.name,
    required this.extension_,
    required this.available,
  });

  @override
  int get hashCode => name.hashCode ^ extension_.hashCode ^ available.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is ConversionTargetDto &&
          runtimeType == other.runtimeType &&
          name == other.name &&
          extension_ == other.extension_ &&
          available == other.available;
}

enum FailureKind {
  validation,
  permission,
  corruptData,
  notFound,
  network,
  cancelled,
  closed,
  unsupported,
  internal,
}

class FileEntryDto {
  final String name;
  final String path;
  final bool directory;

  const FileEntryDto({
    required this.name,
    required this.path,
    required this.directory,
  });

  @override
  int get hashCode => name.hashCode ^ path.hashCode ^ directory.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is FileEntryDto &&
          runtimeType == other.runtimeType &&
          name == other.name &&
          path == other.path &&
          directory == other.directory;
}

class LibraryPage {
  final List<TrackDto> tracks;
  final int total;
  final int revision;
  final List<String> genres;
  final List<String> artists;
  final List<String> albums;

  const LibraryPage({
    required this.tracks,
    required this.total,
    required this.revision,
    required this.genres,
    required this.artists,
    required this.albums,
  });

  @override
  int get hashCode =>
      tracks.hashCode ^
      total.hashCode ^
      revision.hashCode ^
      genres.hashCode ^
      artists.hashCode ^
      albums.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is LibraryPage &&
          runtimeType == other.runtimeType &&
          tracks == other.tracks &&
          total == other.total &&
          revision == other.revision &&
          genres == other.genres &&
          artists == other.artists &&
          albums == other.albums;
}

class LibraryQuery {
  final String text;
  final String genre;
  final String artist;
  final String album;
  final SmartView smart;
  final int offset;
  final int limit;

  const LibraryQuery({
    required this.text,
    required this.genre,
    required this.artist,
    required this.album,
    required this.smart,
    required this.offset,
    required this.limit,
  });

  static Future<LibraryQuery> default_() =>
      RustLib.instance.api.crateApiModelsLibraryQueryDefault();

  @override
  int get hashCode =>
      text.hashCode ^
      genre.hashCode ^
      artist.hashCode ^
      album.hashCode ^
      smart.hashCode ^
      offset.hashCode ^
      limit.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is LibraryQuery &&
          runtimeType == other.runtimeType &&
          text == other.text &&
          genre == other.genre &&
          artist == other.artist &&
          album == other.album &&
          smart == other.smart &&
          offset == other.offset &&
          limit == other.limit;
}

class NamedItem {
  final int id;
  final String name;

  const NamedItem({required this.id, required this.name});

  @override
  int get hashCode => id.hashCode ^ name.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is NamedItem &&
          runtimeType == other.runtimeType &&
          id == other.id &&
          name == other.name;
}

class PlaybackDto {
  final TrackDto? current;
  final int? cursor;
  final PlaybackState state;
  final int position;
  final int duration;
  final Float32List spectrum;
  final int libraryRevision;
  final int queueRevision;
  final int catalogRevision;
  final PreferencesDto preferences;
  final bool busy;
  final bool canCancel;
  final bool canUndo;
  final bool canRedo;
  final String status;
  final String? error;
  final bool shutdown;

  const PlaybackDto({
    this.current,
    this.cursor,
    required this.state,
    required this.position,
    required this.duration,
    required this.spectrum,
    required this.libraryRevision,
    required this.queueRevision,
    required this.catalogRevision,
    required this.preferences,
    required this.busy,
    required this.canCancel,
    required this.canUndo,
    required this.canRedo,
    required this.status,
    this.error,
    required this.shutdown,
  });

  @override
  int get hashCode =>
      current.hashCode ^
      cursor.hashCode ^
      state.hashCode ^
      position.hashCode ^
      duration.hashCode ^
      spectrum.hashCode ^
      libraryRevision.hashCode ^
      queueRevision.hashCode ^
      catalogRevision.hashCode ^
      preferences.hashCode ^
      busy.hashCode ^
      canCancel.hashCode ^
      canUndo.hashCode ^
      canRedo.hashCode ^
      status.hashCode ^
      error.hashCode ^
      shutdown.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is PlaybackDto &&
          runtimeType == other.runtimeType &&
          current == other.current &&
          cursor == other.cursor &&
          state == other.state &&
          position == other.position &&
          duration == other.duration &&
          spectrum == other.spectrum &&
          libraryRevision == other.libraryRevision &&
          queueRevision == other.queueRevision &&
          catalogRevision == other.catalogRevision &&
          preferences == other.preferences &&
          busy == other.busy &&
          canCancel == other.canCancel &&
          canUndo == other.canUndo &&
          canRedo == other.canRedo &&
          status == other.status &&
          error == other.error &&
          shutdown == other.shutdown;
}

enum PlaybackState { empty, stopped, playing, paused }

class PreferencesDto {
  final String theme;
  final int volume;
  final Float64List equalizer;
  final int repeat;
  final int shuffle;
  final int windowWidth;
  final int windowHeight;

  const PreferencesDto({
    required this.theme,
    required this.volume,
    required this.equalizer,
    required this.repeat,
    required this.shuffle,
    required this.windowWidth,
    required this.windowHeight,
  });

  @override
  int get hashCode =>
      theme.hashCode ^
      volume.hashCode ^
      equalizer.hashCode ^
      repeat.hashCode ^
      shuffle.hashCode ^
      windowWidth.hashCode ^
      windowHeight.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is PreferencesDto &&
          runtimeType == other.runtimeType &&
          theme == other.theme &&
          volume == other.volume &&
          equalizer == other.equalizer &&
          repeat == other.repeat &&
          shuffle == other.shuffle &&
          windowWidth == other.windowWidth &&
          windowHeight == other.windowHeight;
}

enum SmartView {
  all,
  topRated,
  recentlyAdded,
  recentlyPlayed,
  neverPlayed,
  mostPlayed,
}

class StationDto {
  final String name;
  final String url;

  const StationDto({required this.name, required this.url});

  @override
  int get hashCode => name.hashCode ^ url.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is StationDto &&
          runtimeType == other.runtimeType &&
          name == other.name &&
          url == other.url;
}

class TagEdit {
  final String path;
  final String title;
  final String artist;
  final String album;
  final String genre;
  final int? year;
  final int? track;

  const TagEdit({
    required this.path,
    required this.title,
    required this.artist,
    required this.album,
    required this.genre,
    this.year,
    this.track,
  });

  @override
  int get hashCode =>
      path.hashCode ^
      title.hashCode ^
      artist.hashCode ^
      album.hashCode ^
      genre.hashCode ^
      year.hashCode ^
      track.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is TagEdit &&
          runtimeType == other.runtimeType &&
          path == other.path &&
          title == other.title &&
          artist == other.artist &&
          album == other.album &&
          genre == other.genre &&
          year == other.year &&
          track == other.track;
}

class TrackDto {
  final String url;
  final String title;
  final String artist;
  final String album;
  final String genre;
  final int year;
  final int track;
  final int duration;
  final double rating;

  const TrackDto({
    required this.url,
    required this.title,
    required this.artist,
    required this.album,
    required this.genre,
    required this.year,
    required this.track,
    required this.duration,
    required this.rating,
  });

  @override
  int get hashCode =>
      url.hashCode ^
      title.hashCode ^
      artist.hashCode ^
      album.hashCode ^
      genre.hashCode ^
      year.hashCode ^
      track.hashCode ^
      duration.hashCode ^
      rating.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is TrackDto &&
          runtimeType == other.runtimeType &&
          url == other.url &&
          title == other.title &&
          artist == other.artist &&
          album == other.album &&
          genre == other.genre &&
          year == other.year &&
          track == other.track &&
          duration == other.duration &&
          rating == other.rating;
}
