// This file is automatically generated, so please do not edit it.
// @generated by `flutter_rust_bridge`@ 2.13.0.

// ignore_for_file: invalid_use_of_internal_member, unused_import, unnecessary_import

import '../frb_generated.dart';
import 'models.dart';

import 'package:flutter_rust_bridge/flutter_rust_bridge_for_generated.dart';

// These functions are ignored because they are not marked as `pub`: `absolute`, `queue_track`, `select_songs`, `song_track`, `validate_query`, `with_cache`
// These types are ignored because they are neither used by any `pub` functions nor (for structs and enums) marked `#[frb(unignore)]`: `Cache`
// These function are ignored because they are on traits that is not defined in current crate (put an empty `#[frb]` on it to unignore): `drop`

/// Capabilities come from the same domain table and factories as conversion.
Future<List<ConversionTargetDto>> conversionTargets() =>
    RustLib.instance.api.crateApiSessionConversionTargets();

Future<List<String>> supportedAudioExtensions() =>
    RustLib.instance.api.crateApiSessionSupportedAudioExtensions();

Future<Session> openSession({
  String? profile,
  required List<String> launchUris,
}) => RustLib.instance.api.crateApiSessionOpenSession(
  profile: profile,
  launchUris: launchUris,
);

Future<List<StationDto>> radioPresets() =>
    RustLib.instance.api.crateApiSessionRadioPresets();

// Rust type: RustOpaqueMoi<flutter_rust_bridge::for_generated::RustAutoOpaqueInner<Session>>
abstract class Session implements RustOpaqueInterface {
  Future<CatalogDto> catalog();

  Future<void> close();

  /// A shared command path for menus, keyboard actions and rendered controls.
  Future<void> dispatch({required Command command});

  /// Small playback/preferences updates; library and queue rows stay separate.
  Future<PlaybackDto> playback();

  Future<LibraryPage> queryLibrary({required LibraryQuery query});

  Future<List<TrackDto>> queue();
}
